# Limpeza de Dados

In [1]:
import wbgapi as wb

In [2]:
def read_data(code):
    worldbank_data = wb.data.DataFrame(code, ['DEU', 'AUS', 'CAN', 'USA', 'FRA', 'ITA', 'JPN', 'GBR', 'ZAF', 'SAU', 'ARG', 'BRA', 'CHN', 'KOR', 'IND', 'IDN', 'MEX', 'RUS', 'TUR'])
    return worldbank_data

## Categoria de Renda

In [3]:
wb.economy.info(['DEU', 'AUS', 'CAN', 'USA', 'FRA', 'ITA', 'JPN', 'GBR', 'ZAF', 'SAU', 'ARG', 'BRA', 'CHN', 'KOR', 'IND', 'IDN', 'MEX', 'RUS', 'TUR'])

id    value               region    incomeLevel
----  ------------------  --------  -------------
ARG   Argentina           LCN       UMC
AUS   Australia           EAS       HIC
BRA   Brazil              LCN       UMC
CAN   Canada              NAC       HIC
CHN   China               EAS       UMC
FRA   France              ECS       HIC
DEU   Germany             ECS       HIC
IND   India               SAS       LMC
IDN   Indonesia           EAS       LMC
ITA   Italy               ECS       HIC
JPN   Japan               EAS       HIC
KOR   Korea, Rep.         EAS       HIC
MEX   Mexico              LCN       UMC
RUS   Russian Federation  ECS       UMC
SAU   Saudi Arabia        MEA       HIC
ZAF   South Africa        SSF       UMC
TUR   Turkey              ECS       UMC
GBR   United Kingdom      ECS       HIC
USA   United States       NAC       HIC
      19 elements

## Agricultura e desenvolvimento rural

### Input

### Agriculture, forestry, and fishing, value added (current US$)

In [4]:
agriculture_forestry_current = read_data('NV.AGR.TOTL.CD')
agriculture_forestry_current

,YR1960,YR1961,YR1962,YR1963,YR1964,YR1965,YR1966,YR1967,YR1968,YR1969,...,YR2011,YR2012,YR2013,YR2014,YR2015,YR2016,YR2017,YR2018,YR2019,YR2020
economy,,,,,,,,,,,,,,,,,,,,,
ARG,NaN,NaN,NaN,NaN,NaN,3.657647e+09,2.942857e+09,2.420909e+09,2.570000e+09,2.871143e+09,...,3.710472e+10,3.156730e+10,3.341363e+10,3.533028e+10,3.066935e+10,3.492692e+10,3.367222e+10,2.741595e+10,2.712047e+10,2.618677e+10
AUS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.179533e+10,3.486183e+10,3.591977e+10,3.252272e+10,3.207089e+10,2.905008e+10,3.594690e+10,3.522518e+10,2.962952e+10,2.526009e+10
BRA,2.679301e+09,2.604793e+09,3.095469e+09,3.482148e+09,3.359594e+09,3.633362e+09,3.603490e+09,3.980945e+09,4.006320e+09,4.148971e+09,...,1.135964e+11,1.027572e+11,1.114471e+11,1.062367e+11,7.784003e+10,8.783404e+10,9.493357e+10,8.473671e+10,8.265677e+10,8.531972e+10
CAN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.166413e+10,3.311804e+10,3.497883e+10,2.864909e+10,2.910416e+10,2.845471e+10,3.117103e+10,NaN,NaN,NaN
CHN,1.383947e+10,1.791778e+10,1.840523e+10,2.020879e+10,2.270696e+10,2.644813e+10,2.852384e+10,2.901129e+10,2.950280e+10,2.990495e+10,...,6.930505e+11,7.776030e+11,8.558713e+11,9.054648e+11,9.277341e+11,9.050974e+11,9.187954e+11,9.786148e+11,1.020115e+12,1.126740e+12
DEU,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.407496e+10,2.990902e+10,3.518645e+10,3.513191e+10,2.297986e+10,2.421809e+10,3.135912e+10,2.739067e+10,3.028962e+10,2.828306e+10
FRA,6.556833e+09,6.125026e+09,7.433735e+09,7.482895e+09,7.508139e+09,7.906731e+09,8.355811e+09,9.001529e+09,9.503755e+09,9.479063e+09,...,4.722145e+10,4.379453e+10,4.100328e+10,4.438986e+10,3.914895e+10,3.551521e+10,3.992912e+10,4.599696e+10,4.154594e+10,4.200198e+10
GBR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.853908e+10,1.740787e+10,1.794389e+10,2.314352e+10,1.898875e+10,1.551778e+10,1.527279e+10,1.625573e+10,1.665337e+10,1.556796e+10
IDN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.206605e+11,1.227557e+11,1.218831e+11,1.188058e+11,1.161520e+11,1.256054e+11,1.336212e+11,1.334993e+11,1.422667e+11,1.450457e+11
IND,1.529810e+10,1.584496e+10,1.617792e+10,1.903938e+10,2.326295e+10,2.319789e+10,1.835786e+10,2.144152e+10,2.210136e+10,2.417312e+10,...,3.134183e+11,3.078725e+11,3.183986e+11,3.424089e+11,3.402450e+11,3.755162e+11,4.390397e+11,4.313718e+11,4.787272e+11,4.805041e+11
ITA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.316796e+10,4.113114e+10,4.592243e+10,4.313649e+10,3.791567e+10,3.617238e+10,3.860446e+10,4.067700e+10,3.827629e+10,3.755324e+10
JPN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6.733493e+10,7.042948e+10,5.560083e+10,4.880373e+10,4.596592e+10,5.629044e+10,5.564157e+10,5.272081e+10,5.185137e+10,NaN
KOR,1.447133e+09,9.351621e+08,1.031004e+09,1.719314e+09,1.609336e+09,1.171246e+09,1.351367e+09,1.466879e+09,1.723152e+09,2.104664e+09,...,2.768620e+10,2.794879e+10,2.877364e+10,3.052763e+10,2.937274e+10,2.788760e+10,3.005446e+10,3.012276e+10,2.671704e+10,2.866575e+10
MEX,NaN,NaN,NaN,NaN,NaN,2.871792e+09,2.941032e+09,3.119800e+09,3.206344e+09,3.393408e+09,...,3.645897e+10,3.812169e+10,4.000201e+10,4.119798e+10,3.740512e+10,3.609131e+10,3.918371e+10,4.123953e+10,4.299388e+10,4.185403e+10
RUS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6.446150e+10,6.461542e+10,6.862749e+10,6.920300e+10,5.280905e+10,4.903139e+10,5.594125e+10,5.625397e+10,5.898589e+10,5.489233e+10
SAU,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.066667e+08,2.206667e+08,...,1.457547e+10,1.530347e+10,1.610747e+10,1.684373e+10,1.713787e+10,1.732060e+10,1.741071e+10,1.749576e+10,1.770962e+10,1.794103e+10
TUR,7.685984e+09,4.133333e+09,4.711111e+09,5.522222e+09,5.644444e+09,5.522222e+09,6.655556e+09,6.966667e+09,7.277778e+09,7.955556e+09,...,6.856010e+10,6.775774e+10,6.394263e+10,6.156933e+10,5.936451e+10,5.341908e+10,5.187160e+10,4.495744e+10,4.890812e+10,4.755225e+10
USA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.890736e+11,1.876956e+11,2.238283e+11,2.077970e+11,1.903835e+11,1.769514e+11,1.856204e+11,1.897446e+11,1.965138e+11,NaN
ZAF,8.077997e+08,8.777996e+08,8.987996e+08,9.785996e+08,9.337996e+08,9.925996e+08,1.118600e+09,1.373399e+09,1.247400e+09,1.311799e+09,...,9.517139e+09,8.598350e+09,7.695187e+09,7.631146e+09,6.634302e+09,6.591156e+09,8.253799e+09,8.014040e+09,6.622879e+09,7.259060e+09

In [5]:
agriculture_forestry_current.loc[:, 'YR1989':]

,YR1989,YR1990,YR1991,YR1992,YR1993,YR1994,YR1995,YR1996,YR1997,YR1998,...,YR2011,YR2012,YR2013,YR2014,YR2015,YR2016,YR2017,YR2018,YR2019,YR2020
economy,,,,,,,,,,,,,,,,,,,,,
ARG,7.369454e+09,1.148301e+10,1.274253e+10,1.370624e+10,1.216101e+10,1.308482e+10,1.380848e+10,1.526996e+10,1.529302e+10,1.570292e+10,...,3.710472e+10,3.156730e+10,3.341363e+10,3.533028e+10,3.066935e+10,3.492692e+10,3.367222e+10,2.741595e+10,2.712047e+10,2.618677e+10
AUS,NaN,1.308119e+10,1.035241e+10,9.920018e+09,1.016793e+10,1.079142e+10,1.109593e+10,1.357891e+10,1.409454e+10,1.212236e+10,...,3.179533e+10,3.486183e+10,3.591977e+10,3.252272e+10,3.207089e+10,2.905008e+10,3.594690e+10,3.522518e+10,2.962952e+10,2.526009e+10
BRA,3.592700e+10,3.175134e+10,4.092700e+10,2.716044e+10,2.873521e+10,4.764273e+10,3.855502e+10,4.055183e+10,4.137832e+10,4.102725e+10,...,1.135964e+11,1.027572e+11,1.114471e+11,1.062367e+11,7.784003e+10,8.783404e+10,9.493357e+10,8.473671e+10,8.265677e+10,8.531972e+10
CAN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.401343e+10,1.374115e+10,...,3.166413e+10,3.311804e+10,3.497883e+10,2.864909e+10,2.910416e+10,2.845471e+10,3.117103e+10,NaN,NaN,NaN
CHN,8.559111e+10,9.593158e+10,9.214020e+10,9.105626e+10,8.586635e+10,1.098982e+11,1.439458e+11,1.669232e+11,1.720817e+11,1.765739e+11,...,6.930505e+11,7.776030e+11,8.558713e+11,9.054648e+11,9.277341e+11,9.050974e+11,9.187954e+11,9.786148e+11,1.020115e+12,1.126740e+12
DEU,NaN,NaN,2.058692e+10,2.143143e+10,1.991719e+10,2.151139e+10,2.574041e+10,2.602547e+10,2.281412e+10,2.183728e+10,...,3.407496e+10,2.990902e+10,3.518645e+10,3.513191e+10,2.297986e+10,2.421809e+10,3.135912e+10,2.739067e+10,3.028962e+10,2.828306e+10
FRA,3.203784e+10,3.981207e+10,3.318335e+10,3.633705e+10,3.036831e+10,3.346526e+10,3.914312e+10,3.860495e+10,3.405934e+10,3.551034e+10,...,4.722145e+10,4.379453e+10,4.100328e+10,4.438986e+10,3.914895e+10,3.551521e+10,3.992912e+10,4.599696e+10,4.154594e+10,4.200198e+10
GBR,NaN,1.425864e+10,1.462241e+10,1.496983e+10,1.358868e+10,1.509451e+10,1.698438e+10,1.559282e+10,1.516208e+10,1.600696e+10,...,1.853908e+10,1.740787e+10,1.794389e+10,2.314352e+10,1.898875e+10,1.551778e+10,1.527279e+10,1.625573e+10,1.665337e+10,1.556796e+10
IDN,2.212575e+10,2.287197e+10,2.292999e+10,2.499267e+10,2.825135e+10,3.057804e+10,3.464209e+10,3.790795e+10,3.471857e+10,1.725928e+10,...,1.206605e+11,1.227557e+11,1.218831e+11,1.188058e+11,1.161520e+11,1.256054e+11,1.336212e+11,1.334993e+11,1.422667e+11,1.450457e+11
IND,7.968851e+10,8.633193e+10,7.382848e+10,7.686453e+10,7.507980e+10,8.636351e+10,8.811364e+10,9.986277e+10,1.012445e+11,1.027205e+11,...,3.134183e+11,3.078725e+11,3.183986e+11,3.424089e+11,3.402450e+11,3.755162e+11,4.390397e+11,4.313718e+11,4.787272e+11,4.805041e+11
ITA,NaN,3.759086e+10,4.036742e+10,4.116146e+10,3.193349e+10,3.288418e+10,3.497801e+10,3.903928e+10,3.554150e+10,3.516594e+10,...,4.316796e+10,4.113114e+10,4.592243e+10,4.313649e+10,3.791567e+10,3.617238e+10,3.860446e+10,4.067700e+10,3.827629e+10,3.755324e+10
JPN,NaN,NaN,NaN,NaN,NaN,9.458280e+10,9.122620e+10,8.140994e+10,6.864070e+10,6.570857e+10,...,6.733493e+10,7.042948e+10,5.560083e+10,4.880373e+10,4.596592e+10,5.629044e+10,5.564157e+10,5.272081e+10,5.185137e+10,NaN
KOR,2.109135e+10,2.155434e+10,2.256508e+10,2.349171e+10,2.322573e+10,2.623250e+10,3.019137e+10,3.026838e+10,2.549748e+10,1.619934e+10,...,2.768620e+10,2.794879e+10,2.877364e+10,3.052763e+10,2.937274e+10,2.788760e+10,3.005446e+10,3.012276e+10,2.671704e+10,2.866575e+10
MEX,1.428610e+10,1.741803e+10,2.034485e+10,2.178575e+10,2.554004e+10,2.436840e+10,1.593280e+10,2.000821e+10,2.226983e+10,2.189566e+10,...,3.645897e+10,3.812169e+10,4.000201e+10,4.119798e+10,3.740512e+10,3.609131e+10,3.918371e+10,4.123953e+10,4.299388e+10,4.185403e+10
RUS,7.902463e+10,7.990485e+10,7.133333e+10,3.343258e+10,3.288016e+10,2.413749e+10,2.647026e+10,2.565553e+10,2.376837e+10,1.382792e+10,...,6.446150e+10,6.461542e+10,6.862749e+10,6.920300e+10,5.280905e+10,4.903139e+10,5.594125e+10,5.625397e+10,5.898589e+10,5.489233e+10
SAU,6.048064e+09,6.713485e+09,7.183445e+09,7.686248e+09,8.070494e+09,8.312684e+09,8.437383e+09,8.587984e+09,8.918621e+09,9.040267e+09,...,1.457547e+10,1.530347e+10,1.610747e+10,1.684373e+10,1.713787e+10,1.732060e+10,1.741071e+10,1.749576e+10,1.770962e+10,1.794103e+10
TUR,1.777078e+10,2.633253e+10,2.287486e+10,2.374299e+10,2.777500e+10,2.020841e+10,2.659777e+10,3.058690e+10,2.745228e+10,3.435881e+10,...,6.856010e+10,6.775774e+10,6.394263e+10,6.156933e+10,5.936451e+10,5.341908e+10,5.187160e+10,4.495744e+10,4.890812e+10,4.755225e+10
USA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.146743e+11,1.100223e+11,...,1.890736e+11,1.876956e+11,2.238283e+11,2.077970e+11,1.903835e+11,1.769514e+11,1.856204e+11,1.897446e+11,1.965138e+11,NaN
ZAF,4.854200e+09,4.861399e+09,5.168580e+09,4.726157e+09,5.144597e+09,5.890504e+09,5.498883e+09,5.697672e+09,5.634332e+09,4.750647e+09,...,9.517139e+09,8.598350e+09,7.695187e+09,7.631146e+09,6.634302e+09,6.591156e+09,8.253799e+09,8.014040e+09,6.622879e+09,7.259060e+09

In [6]:
agriculture_forestry_current.info()

<class 'pandas.core.frame.DataFrame'>
Index: 19 entries, ARG to ZAF
Data columns (total 61 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   YR1960  7 non-null      float64
 1   YR1961  7 non-null      float64
 2   YR1962  7 non-null      float64
 3   YR1963  7 non-null      float64
 4   YR1964  7 non-null      float64
 5   YR1965  9 non-null      float64
 6   YR1966  9 non-null      float64
 7   YR1967  9 non-null      float64
 8   YR1968  10 non-null     float64
 9   YR1969  10 non-null     float64
 10  YR1970  10 non-null     float64
 11  YR1971  10 non-null     float64
 12  YR1972  10 non-null     float64
 13  YR1973  10 non-null     float64
 14  YR1974  10 non-null     float64
 15  YR1975  10 non-null     float64
 16  YR1976  10 non-null     float64
 17  YR1977  10 non-null     float64
 18  YR1978  10 non-null     float64
 19  YR1979  10 non-null     float64
 20  YR1980  10 non-null     float64
 21  YR1981  10 non-null     float64
 22  YR1982  10 non-null     float64
 23  YR1983  11 non-null     float64
 24  YR1984  11 non-null     float64
 25  YR1985  11 non-null     float64
 26  YR1986  11 non-null     float64
 27  YR1987  11 non-null     float64
 28  YR1988  11 non-null     float64
 29  YR1989  12 non-null     float64
 30  YR1990  15 non-null     float64
 31  YR1991  16 non-null     float64
 32  YR1992  16 non-null     float64
 33  YR1993  16 non-null     float64
 34  YR1994  17 non-null     float64
 35  YR1995  17 non-null     float64
 36  YR1996  17 non-null     float64
 37  YR1997  19 non-null     float64
 38  YR1998  19 non-null     float64
 39  YR1999  19 non-null     float64
 40  YR2000  19 non-null     float64
 41  YR2001  19 non-null     float64
 42  YR2002  19 non-null     float64
 43  YR2003  19 non-null     float64
 44  YR2004  19 non-null     float64
 45  YR2005  19 non-null     float64
 46  YR2006  19 non-null     float64
 47  YR2007  19 non-null     float64
 48  YR2008  19 non-null     float64
 49  YR2009  19 non-null     float64
 50  YR2010  19 non-null     float64
 51  YR2011  19 non-null     float64
 52  YR2012  19 non-null     float64
 53  YR2013  19 non-null     float64
 54  YR2014  19 non-null     float64
 55  YR2015  19 non-null     float64
 56  YR2016  19 non-null     float64
 57  YR2017  19 non-null     float64
 58  YR2018  18 non-null     float64
 59  YR2019  18 non-null     float64
 60  YR2020  16 non-null     float64
dtypes: float64(61)
memory usage: 9.2+ KB

In [7]:
agriculture_forestry_current.drop(agriculture_forestry_current.loc[:, :'YR1989'], axis = 1, inplace=True)
agriculture_forestry_current.fillna(agriculture_forestry_current.mean(), inplace=True)

### Output

#### Employment in agriculture (% of total employment) (modeled ILO estimate)

In [8]:
employment_agriculture = read_data('SL.AGR.EMPL.ZS')
employment_agriculture

,YR1960,YR1961,YR1962,YR1963,YR1964,YR1965,YR1966,YR1967,YR1968,YR1969,...,YR2011,YR2012,YR2013,YR2014,YR2015,YR2016,YR2017,YR2018,YR2019,YR2020
economy,,,,,,,,,,,,,,,,,,,,,
ARG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.640000,0.620000,0.62,0.550000,0.260000,0.130000,0.060000,0.100000,0.060000,NaN
AUS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.820000,2.800000,2.62,2.800000,2.640000,2.620000,2.600000,2.620000,2.560000,NaN
BRA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,11.990000,11.470000,11.17,10.340000,10.200000,10.140000,9.460000,9.260000,9.080000,NaN
CAN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.790000,1.750000,1.78,1.710000,1.640000,1.580000,1.520000,1.490000,1.510000,NaN
CHN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,34.799999,33.599998,31.40,29.500000,28.590000,27.700001,26.980000,26.070000,25.330000,NaN
DEU,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.650000,1.560000,1.45,1.430000,1.390000,1.310000,1.280000,1.250000,1.210000,NaN
FRA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.910000,2.920000,3.08,2.850000,2.710000,2.860000,2.610000,2.500000,2.530000,NaN
GBR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.220000,1.190000,1.06,1.260000,1.140000,1.130000,1.160000,1.070000,1.050000,NaN
IDN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,37.189999,35.930000,34.98,34.279999,33.040001,31.820000,30.790001,29.629999,28.500000,NaN
IND,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,49.259998,47.000000,46.50,45.889999,45.259998,44.560001,43.930000,43.330002,42.599998,NaN
ITA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.680000,3.690000,3.60,3.640000,3.750000,3.880000,3.780000,3.760000,3.890000,NaN
JPN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.970000,3.870000,3.75,3.690000,3.630000,3.500000,3.440000,3.490000,3.380000,NaN
KOR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6.370000,6.130000,6.76,5.580000,5.230000,4.940000,4.920000,5.000000,5.140000,NaN
MEX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,13.690000,13.720000,13.65,13.770000,13.430000,13.100000,13.120000,12.810000,12.480000,NaN
RUS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,7.690000,7.330000,6.99,6.720000,6.710000,6.720000,5.900000,5.880000,5.830000,NaN
SAU,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.260000,4.360000,4.45,5.260000,6.100000,4.970000,3.560000,2.520000,2.410000,NaN
TUR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,24.160000,23.559999,22.92,21.090000,20.410000,19.500000,19.379999,18.430000,18.110001,NaN
USA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.450000,1.380000,1.32,1.350000,1.440000,1.430000,1.430000,1.370000,1.360000,NaN
ZAF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.600000,4.830000,4.98,4.650000,5.610000,5.570000,5.280000,5.160000,5.280000,NaN

In [9]:
employment_agriculture.info()

<class 'pandas.core.frame.DataFrame'>
Index: 19 entries, ARG to ZAF
Data columns (total 61 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   YR1960  0 non-null      float64
 1   YR1961  0 non-null      float64
 2   YR1962  0 non-null      float64
 3   YR1963  0 non-null      float64
 4   YR1964  0 non-null      float64
 5   YR1965  0 non-null      float64
 6   YR1966  0 non-null      float64
 7   YR1967  0 non-null      float64
 8   YR1968  0 non-null      float64
 9   YR1969  0 non-null      float64
 10  YR1970  0 non-null      float64
 11  YR1971  0 non-null      float64
 12  YR1972  0 non-null      float64
 13  YR1973  0 non-null      float64
 14  YR1974  0 non-null      float64
 15  YR1975  0 non-null      float64
 16  YR1976  0 non-null      float64
 17  YR1977  0 non-null      float64
 18  YR1978  0 non-null      float64
 19  YR1979  0 non-null      float64
 20  YR1980  0 non-null      float64
 21  YR1981  0 non-null      float64
 22  YR1982  0 non-null      float64
 23  YR1983  0 non-null      float64
 24  YR1984  0 non-null      float64
 25  YR1985  0 non-null      float64
 26  YR1986  0 non-null      float64
 27  YR1987  0 non-null      float64
 28  YR1988  0 non-null      float64
 29  YR1989  0 non-null      float64
 30  YR1990  0 non-null      float64
 31  YR1991  19 non-null     float64
 32  YR1992  19 non-null     float64
 33  YR1993  19 non-null     float64
 34  YR1994  19 non-null     float64
 35  YR1995  19 non-null     float64
 36  YR1996  19 non-null     float64
 37  YR1997  19 non-null     float64
 38  YR1998  19 non-null     float64
 39  YR1999  19 non-null     float64
 40  YR2000  19 non-null     float64
 41  YR2001  19 non-null     float64
 42  YR2002  19 non-null     float64
 43  YR2003  19 non-null     float64
 44  YR2004  19 non-null     float64
 45  YR2005  19 non-null     float64
 46  YR2006  19 non-null     float64
 47  YR2007  19 non-null     float64
 48  YR2008  19 non-null     float64
 49  YR2009  19 non-null     float64
 50  YR2010  19 non-null     float64
 51  YR2011  19 non-null     float64
 52  YR2012  19 non-null     float64
 53  YR2013  19 non-null     float64
 54  YR2014  19 non-null     float64
 55  YR2015  19 non-null     float64
 56  YR2016  19 non-null     float64
 57  YR2017  19 non-null     float64
 58  YR2018  19 non-null     float64
 59  YR2019  19 non-null     float64
 60  YR2020  0 non-null      float64
dtypes: float64(61)
memory usage: 9.2+ KB

In [10]:
employment_agriculture.dropna(axis = 1, inplace=True)

#### Rural population (% of total population)

In [11]:
rural_population = read_data('SP.RUR.TOTL.ZS')
rural_population

,YR1960,YR1961,YR1962,YR1963,YR1964,YR1965,YR1966,YR1967,YR1968,YR1969,...,YR2011,YR2012,YR2013,YR2014,YR2015,YR2016,YR2017,YR2018,YR2019,YR2020
economy,,,,,,,,,,,,,,,,,,,,,
ARG,26.389,25.783,25.233,24.691,24.156,23.631,23.112,22.602,22.099,21.606,...,9.010,8.879,8.751,8.623,8.497,8.373,8.251,8.130,8.009,7.889
AUS,18.471,18.059,17.772,17.489,17.208,16.932,16.660,16.493,16.328,16.164,...,14.700,14.598,14.498,14.398,14.299,14.200,14.096,13.988,13.876,13.759
BRA,53.861,52.878,51.901,50.922,49.941,48.963,47.984,47.007,46.030,45.060,...,15.369,15.077,14.791,14.508,14.230,13.958,13.691,13.431,13.176,12.927
CAN,30.939,30.332,29.506,28.693,27.893,27.108,26.358,25.845,25.338,24.839,...,18.904,18.863,18.822,18.782,18.741,18.700,18.650,18.589,18.518,18.438
CHN,83.797,83.292,82.774,82.243,81.701,81.914,82.085,82.215,82.344,82.472,...,49.489,48.235,46.987,45.741,44.500,43.264,42.040,40.848,39.692,38.572
DEU,28.616,28.303,28.238,28.174,28.109,28.045,27.981,27.917,27.853,27.789,...,22.840,22.830,22.820,22.810,22.800,22.776,22.739,22.688,22.624,22.547
FRA,38.120,37.393,36.511,35.298,34.102,32.929,31.775,30.643,29.762,29.352,...,21.378,21.122,20.865,20.606,20.345,20.083,19.820,19.556,19.291,19.025
GBR,21.556,21.626,21.763,21.901,22.040,22.179,22.318,22.459,22.600,22.741,...,18.430,18.163,17.898,17.635,17.374,17.114,16.857,16.602,16.348,16.097
IDN,85.414,85.179,84.942,84.701,84.457,84.211,83.961,83.707,83.451,83.191,...,49.405,48.724,48.045,47.365,46.687,46.011,45.341,44.675,44.015,43.359
IND,82.076,81.968,81.782,81.595,81.405,81.215,81.023,80.829,80.634,80.438,...,68.724,68.366,67.997,67.616,67.223,66.818,66.400,65.970,65.528,65.074
ITA,40.639,40.144,39.645,39.147,38.650,38.157,37.666,37.178,36.691,36.208,...,31.556,31.316,31.021,30.728,30.435,30.145,29.856,29.562,29.264,28.961
JPN,36.728,35.787,34.856,33.936,33.028,32.134,31.296,30.484,29.684,28.898,...,8.931,8.852,8.774,8.696,8.619,8.543,8.465,8.384,8.302,8.218
KOR,72.290,71.469,70.539,69.593,68.628,67.649,66.653,65.029,63.154,61.244,...,18.077,18.149,18.221,18.293,18.366,18.438,18.497,18.541,18.570,18.586
MEX,49.247,48.410,47.572,46.735,45.900,45.069,44.239,43.413,42.589,41.771,...,21.889,21.595,21.301,21.007,20.715,20.423,20.133,19.844,19.556,19.269
RUS,46.269,45.374,44.482,43.592,42.706,41.827,40.952,40.082,39.217,38.362,...,26.268,26.209,26.137,26.050,25.950,25.836,25.708,25.567,25.413,25.246
SAU,68.750,67.627,66.482,64.989,63.128,61.231,59.298,57.335,55.346,53.345,...,17.698,17.480,17.260,17.040,16.820,16.599,16.378,16.156,15.935,15.713
TUR,68.485,67.936,67.402,66.863,66.320,65.773,65.051,64.241,63.423,62.599,...,28.598,28.026,27.469,26.923,26.389,25.866,25.356,24.857,24.370,23.895
USA,30.004,29.623,29.243,28.866,28.492,28.121,27.753,27.388,27.026,26.667,...,19.056,18.881,18.701,18.517,18.329,18.138,17.942,17.744,17.541,17.336
ZAF,53.381,53.207,53.094,52.980,52.866,52.752,52.638,52.524,52.410,52.296,...,37.254,36.728,36.207,35.688,35.172,34.659,34.150,33.645,33.144,32.646

In [12]:
rural_population.info()

<class 'pandas.core.frame.DataFrame'>
Index: 19 entries, ARG to ZAF
Data columns (total 61 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   YR1960  19 non-null     float64
 1   YR1961  19 non-null     float64
 2   YR1962  19 non-null     float64
 3   YR1963  19 non-null     float64
 4   YR1964  19 non-null     float64
 5   YR1965  19 non-null     float64
 6   YR1966  19 non-null     float64
 7   YR1967  19 non-null     float64
 8   YR1968  19 non-null     float64
 9   YR1969  19 non-null     float64
 10  YR1970  19 non-null     float64
 11  YR1971  19 non-null     float64
 12  YR1972  19 non-null     float64
 13  YR1973  19 non-null     float64
 14  YR1974  19 non-null     float64
 15  YR1975  19 non-null     float64
 16  YR1976  19 non-null     float64
 17  YR1977  19 non-null     float64
 18  YR1978  19 non-null     float64
 19  YR1979  19 non-null     float64
 20  YR1980  19 non-null     float64
 21  YR1981  19 non-null     float64
 22  YR1982  19 non-null     float64
 23  YR1983  19 non-null     float64
 24  YR1984  19 non-null     float64
 25  YR1985  19 non-null     float64
 26  YR1986  19 non-null     float64
 27  YR1987  19 non-null     float64
 28  YR1988  19 non-null     float64
 29  YR1989  19 non-null     float64
 30  YR1990  19 non-null     float64
 31  YR1991  19 non-null     float64
 32  YR1992  19 non-null     float64
 33  YR1993  19 non-null     float64
 34  YR1994  19 non-null     float64
 35  YR1995  19 non-null     float64
 36  YR1996  19 non-null     float64
 37  YR1997  19 non-null     float64
 38  YR1998  19 non-null     float64
 39  YR1999  19 non-null     float64
 40  YR2000  19 non-null     float64
 41  YR2001  19 non-null     float64
 42  YR2002  19 non-null     float64
 43  YR2003  19 non-null     float64
 44  YR2004  19 non-null     float64
 45  YR2005  19 non-null     float64
 46  YR2006  19 non-null     float64
 47  YR2007  19 non-null     float64
 48  YR2008  19 non-null     float64
 49  YR2009  19 non-null     float64
 50  YR2010  19 non-null     float64
 51  YR2011  19 non-null     float64
 52  YR2012  19 non-null     float64
 53  YR2013  19 non-null     float64
 54  YR2014  19 non-null     float64
 55  YR2015  19 non-null     float64
 56  YR2016  19 non-null     float64
 57  YR2017  19 non-null     float64
 58  YR2018  19 non-null     float64
 59  YR2019  19 non-null     float64
 60  YR2020  19 non-null     float64
dtypes: float64(61)
memory usage: 9.2+ KB

#### Food production index (2014-2016 = 100)

In [80]:
food_production = read_data('AG.PRD.FOOD.XD')
food_production

,YR1960,YR1961,YR1962,YR1963,YR1964,YR1965,YR1966,YR1967,YR1968,YR1969,...,YR2011,YR2012,YR2013,YR2014,YR2015,YR2016,YR2017,YR2018,YR2019,YR2020
economy,,,,,,,,,,,,,,,,,,,,,
ARG,NaN,31.51,33.30,36.31,33.75,32.03,35.65,39.07,37.05,39.93,...,92.81,86.35,94.07,95.12,104.15,100.73,105.56,97.20,NaN,NaN
AUS,NaN,32.91,37.37,39.13,41.54,40.04,43.94,39.88,46.04,43.75,...,91.14,96.40,97.17,101.14,101.28,97.58,107.28,96.97,NaN,NaN
BRA,NaN,12.25,12.75,13.29,13.87,15.34,15.03,16.03,16.74,17.21,...,92.38,91.16,97.61,99.13,101.80,99.07,106.98,107.66,NaN,NaN
CAN,NaN,30.61,36.56,39.37,37.84,41.32,44.72,40.21,43.00,43.40,...,87.48,89.98,103.47,95.04,98.32,106.64,107.09,106.26,NaN,NaN
CHN,NaN,11.76,12.45,12.99,13.79,14.99,16.08,16.30,16.23,16.52,...,91.95,94.92,96.31,97.81,100.85,101.35,102.58,103.09,NaN,NaN
DEU,NaN,71.93,78.87,82.32,80.71,77.82,81.82,88.16,88.79,85.24,...,95.22,96.14,97.09,102.97,99.27,97.76,97.49,93.17,NaN,NaN
FRA,NaN,69.13,78.73,74.49,74.35,78.71,75.21,80.22,83.04,78.36,...,100.79,97.67,96.15,102.50,102.23,95.28,101.62,98.70,NaN,NaN
GBR,NaN,66.75,69.93,69.78,71.28,73.29,72.11,74.71,74.19,74.26,...,96.68,90.86,92.82,100.63,101.40,97.97,102.09,99.40,NaN,NaN
IDN,NaN,18.66,20.32,19.13,20.60,20.15,20.71,19.89,23.01,23.18,...,90.34,96.18,96.22,96.42,99.79,103.79,107.01,108.90,NaN,NaN
IND,NaN,23.17,22.84,23.35,23.90,22.80,22.69,24.10,25.57,26.40,...,90.87,92.97,96.99,99.49,98.28,102.23,107.77,111.77,NaN,NaN
ITA,NaN,86.05,86.79,86.10,90.29,93.15,95.56,101.46,98.35,101.47,...,107.84,103.52,101.77,95.58,102.55,101.88,98.07,100.53,NaN,NaN
JPN,NaN,74.60,78.77,80.14,82.45,84.21,85.62,91.20,95.69,95.01,...,95.52,97.10,101.33,101.05,99.63,99.32,99.56,99.15,NaN,NaN
KOR,NaN,24.38,23.02,25.58,30.55,30.85,32.95,30.57,31.14,35.68,...,89.89,93.82,98.31,102.03,99.65,98.33,97.50,100.71,NaN,NaN
MEX,NaN,18.65,20.08,20.75,22.48,24.41,26.35,26.76,27.49,27.96,...,87.08,91.88,94.41,97.26,98.43,104.31,108.13,110.58,NaN,NaN
RUS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,91.29,84.67,92.44,97.67,100.13,102.21,107.21,104.50,NaN,NaN
SAU,NaN,11.61,11.40,11.55,11.80,12.51,12.61,13.35,11.67,13.90,...,103.72,100.50,110.63,91.53,101.00,107.47,109.31,113.29,NaN,NaN
TUR,NaN,28.21,29.09,29.96,30.06,29.75,32.18,32.49,33.94,33.85,...,88.78,94.52,97.79,95.58,102.19,102.23,107.25,105.58,NaN,NaN
USA,NaN,41.33,41.39,43.03,43.58,45.44,46.40,48.76,49.29,49.92,...,91.56,91.08,96.01,98.34,96.97,104.69,103.35,105.95,NaN,NaN
ZAF,NaN,32.41,33.00,34.58,33.41,35.03,36.81,43.95,38.75,40.92,...,89.68,92.63,97.82,103.42,100.62,95.97,105.40,103.62,NaN,NaN

In [85]:
food_production.info()

<class 'pandas.core.frame.DataFrame'>
Index: 19 entries, ARG to ZAF
Data columns (total 58 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   YR1961  19 non-null     float64
 1   YR1962  19 non-null     float64
 2   YR1963  19 non-null     float64
 3   YR1964  19 non-null     float64
 4   YR1965  19 non-null     float64
 5   YR1966  19 non-null     float64
 6   YR1967  19 non-null     float64
 7   YR1968  19 non-null     float64
 8   YR1969  19 non-null     float64
 9   YR1970  19 non-null     float64
 10  YR1971  19 non-null     float64
 11  YR1972  19 non-null     float64
 12  YR1973  19 non-null     float64
 13  YR1974  19 non-null     float64
 14  YR1975  19 non-null     float64
 15  YR1976  19 non-null     float64
 16  YR1977  19 non-null     float64
 17  YR1978  19 non-null     float64
 18  YR1979  19 non-null     float64
 19  YR1980  19 non-null     float64
 20  YR1981  19 non-null     float64
 21  YR1982  19 non-null     float64
 22  YR1983  19 non-null     float64
 23  YR1984  19 non-null     float64
 24  YR1985  19 non-null     float64
 25  YR1986  19 non-null     float64
 26  YR1987  19 non-null     float64
 27  YR1988  19 non-null     float64
 28  YR1989  19 non-null     float64
 29  YR1990  19 non-null     float64
 30  YR1991  19 non-null     float64
 31  YR1992  19 non-null     float64
 32  YR1993  19 non-null     float64
 33  YR1994  19 non-null     float64
 34  YR1995  19 non-null     float64
 35  YR1996  19 non-null     float64
 36  YR1997  19 non-null     float64
 37  YR1998  19 non-null     float64
 38  YR1999  19 non-null     float64
 39  YR2000  19 non-null     float64
 40  YR2001  19 non-null     float64
 41  YR2002  19 non-null     float64
 42  YR2003  19 non-null     float64
 43  YR2004  19 non-null     float64
 44  YR2005  19 non-null     float64
 45  YR2006  19 non-null     float64
 46  YR2007  19 non-null     float64
 47  YR2008  19 non-null     float64
 48  YR2009  19 non-null     float64
 49  YR2010  19 non-null     float64
 50  YR2011  19 non-null     float64
 51  YR2012  19 non-null     float64
 52  YR2013  19 non-null     float64
 53  YR2014  19 non-null     float64
 54  YR2015  19 non-null     float64
 55  YR2016  19 non-null     float64
 56  YR2017  19 non-null     float64
 57  YR2018  19 non-null     float64
dtypes: float64(58)
memory usage: 8.8+ KB

In [84]:
food_production.fillna(food_production.mean(), inplace=True)
food_production.drop(['YR1960', 'YR2019', 'YR2020'], axis = 1, inplace=True)

## Educação

### Input

#### Expenditure on primary education (% of government expenditure on education)

In [13]:
expenditure_primary = read_data('SE.XPD.PRIM.ZS')
expenditure_primary

,YR1960,YR1961,YR1962,YR1963,YR1964,YR1965,YR1966,YR1967,YR1968,YR1969,...,YR2011,YR2012,YR2013,YR2014,YR2015,YR2016,YR2017,YR2018,YR2019,YR2020
economy,,,,,,,,,,,,,,,,,,,,,
ARG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,31.96866,31.79885,30.03234,30.06039,30.04134,30.07402,29.59458,NaN,NaN,NaN
AUS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,35.97164,34.14038,32.81864,32.62542,31.78434,32.99107,NaN,NaN,NaN,NaN
BRA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,29.28556,28.57004,28.07656,26.81877,25.61507,NaN,NaN,NaN,NaN,NaN
CAN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CHN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
DEU,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,13.21104,12.81050,12.78433,12.79340,12.93305,12.92094,NaN,NaN,NaN,NaN
FRA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
GBR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,30.77206,NaN,29.78850,28.91542,32.16658,32.32674,NaN,NaN,NaN,NaN
IDN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,41.76111,42.46006,43.67680,42.59993,NaN,NaN,NaN,NaN,NaN
IND,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,26.54745,27.21284,28.40116,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ITA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,24.72651,23.97914,24.39744,24.48862,24.97218,23.94555,NaN,NaN,NaN,NaN
JPN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,33.39922,33.08188,NaN,35.11972,NaN,NaN,NaN,NaN
KOR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,31.69974,NaN,NaN,NaN,NaN
MEX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,35.50244,34.66095,37.75482,32.75753,32.46972,32.45208,NaN,NaN,NaN,NaN
RUS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
SAU,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TUR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
USA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,31.10906,30.96455,NaN,NaN,NaN,NaN,NaN,NaN
ZAF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,40.49419,39.91602,NaN,38.79543,NaN,NaN,38.88623,38.74843,NaN,NaN

In [14]:
expenditure_primary.info()

<class 'pandas.core.frame.DataFrame'>
Index: 19 entries, ARG to ZAF
Data columns (total 61 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   YR1960  0 non-null      float64
 1   YR1961  0 non-null      float64
 2   YR1962  0 non-null      float64
 3   YR1963  0 non-null      float64
 4   YR1964  0 non-null      float64
 5   YR1965  0 non-null      float64
 6   YR1966  0 non-null      float64
 7   YR1967  0 non-null      float64
 8   YR1968  0 non-null      float64
 9   YR1969  0 non-null      float64
 10  YR1970  3 non-null      float64
 11  YR1971  3 non-null      float64
 12  YR1972  5 non-null      float64
 13  YR1973  4 non-null      float64
 14  YR1974  4 non-null      float64
 15  YR1975  5 non-null      float64
 16  YR1976  5 non-null      float64
 17  YR1977  4 non-null      float64
 18  YR1978  4 non-null      float64
 19  YR1979  5 non-null      float64
 20  YR1980  5 non-null      float64
 21  YR1981  5 non-null      float64
 22  YR1982  6 non-null      float64
 23  YR1983  7 non-null      float64
 24  YR1984  7 non-null      float64
 25  YR1985  7 non-null      float64
 26  YR1986  7 non-null      float64
 27  YR1987  5 non-null      float64
 28  YR1988  5 non-null      float64
 29  YR1989  5 non-null      float64
 30  YR1990  5 non-null      float64
 31  YR1991  4 non-null      float64
 32  YR1992  5 non-null      float64
 33  YR1993  7 non-null      float64
 34  YR1994  8 non-null      float64
 35  YR1995  9 non-null      float64
 36  YR1996  6 non-null      float64
 37  YR1997  0 non-null      float64
 38  YR1998  8 non-null      float64
 39  YR1999  10 non-null     float64
 40  YR2000  8 non-null      float64
 41  YR2001  6 non-null      float64
 42  YR2002  6 non-null      float64
 43  YR2003  6 non-null      float64
 44  YR2004  7 non-null      float64
 45  YR2005  8 non-null      float64
 46  YR2006  9 non-null      float64
 47  YR2007  9 non-null      float64
 48  YR2008  9 non-null      float64
 49  YR2009  10 non-null     float64
 50  YR2010  10 non-null     float64
 51  YR2011  9 non-null      float64
 52  YR2012  9 non-null      float64
 53  YR2013  11 non-null     float64
 54  YR2014  11 non-null     float64
 55  YR2015  8 non-null      float64
 56  YR2016  8 non-null      float64
 57  YR2017  2 non-null      float64
 58  YR2018  1 non-null      float64
 59  YR2019  0 non-null      float64
 60  YR2020  0 non-null      float64
dtypes: float64(61)
memory usage: 9.2+ KB

#### Expenditure on secondary education (% of government expenditure on education)

In [15]:
expenditure_secondary = read_data('SE.XPD.SECO.ZS')
expenditure_secondary

,YR1960,YR1961,YR1962,YR1963,YR1964,YR1965,YR1966,YR1967,YR1968,YR1969,...,YR2011,YR2012,YR2013,YR2014,YR2015,YR2016,YR2017,YR2018,YR2019,YR2020
economy,,,,,,,,,,,,,,,,,,,,,
ARG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,40.47189,40.43839,41.52728,41.47732,41.33272,40.93612,39.53940,NaN,NaN,NaN
AUS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,36.59127,35.26151,33.06493,32.36199,30.52541,31.27629,NaN,NaN,NaN,NaN
BRA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,45.11796,44.11814,44.99812,43.09467,41.37080,NaN,NaN,NaN,NaN,NaN
CAN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,26.40425,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CHN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
DEU,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,44.55401,43.15876,42.52851,41.96527,41.85471,41.25655,NaN,NaN,NaN,NaN
FRA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
GBR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,41.57060,NaN,40.13864,41.13215,41.03583,37.83738,NaN,NaN,NaN,NaN
IDN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,26.03779,26.03539,26.79933,26.99605,NaN,NaN,NaN,NaN,NaN
IND,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,36.96254,38.73250,41.35294,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ITA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,42.47051,42.97316,42.70249,42.41115,42.74304,NaN,NaN,NaN,NaN,NaN
JPN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,38.36741,37.80486,NaN,41.98022,NaN,NaN,NaN,NaN
KOR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,38.67885,NaN,NaN,NaN,NaN
MEX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,30.66226,31.36863,35.20388,31.98210,32.31004,32.94466,NaN,NaN,NaN,NaN
RUS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
SAU,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TUR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
USA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,35.16779,34.55486,NaN,NaN,NaN,NaN,NaN,NaN
ZAF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,32.91663,30.25606,NaN,30.72001,30.66833,NaN,29.41027,30.76076,NaN,NaN

In [16]:
expenditure_secondary.info()

<class 'pandas.core.frame.DataFrame'>
Index: 19 entries, ARG to ZAF
Data columns (total 61 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   YR1960  0 non-null      float64
 1   YR1961  0 non-null      float64
 2   YR1962  0 non-null      float64
 3   YR1963  0 non-null      float64
 4   YR1964  0 non-null      float64
 5   YR1965  0 non-null      float64
 6   YR1966  0 non-null      float64
 7   YR1967  0 non-null      float64
 8   YR1968  0 non-null      float64
 9   YR1969  0 non-null      float64
 10  YR1970  3 non-null      float64
 11  YR1971  3 non-null      float64
 12  YR1972  5 non-null      float64
 13  YR1973  4 non-null      float64
 14  YR1974  4 non-null      float64
 15  YR1975  5 non-null      float64
 16  YR1976  5 non-null      float64
 17  YR1977  4 non-null      float64
 18  YR1978  4 non-null      float64
 19  YR1979  5 non-null      float64
 20  YR1980  5 non-null      float64
 21  YR1981  5 non-null      float64
 22  YR1982  6 non-null      float64
 23  YR1983  7 non-null      float64
 24  YR1984  7 non-null      float64
 25  YR1985  7 non-null      float64
 26  YR1986  7 non-null      float64
 27  YR1987  5 non-null      float64
 28  YR1988  5 non-null      float64
 29  YR1989  6 non-null      float64
 30  YR1990  5 non-null      float64
 31  YR1991  4 non-null      float64
 32  YR1992  5 non-null      float64
 33  YR1993  7 non-null      float64
 34  YR1994  8 non-null      float64
 35  YR1995  9 non-null      float64
 36  YR1996  7 non-null      float64
 37  YR1997  0 non-null      float64
 38  YR1998  8 non-null      float64
 39  YR1999  10 non-null     float64
 40  YR2000  7 non-null      float64
 41  YR2001  6 non-null      float64
 42  YR2002  6 non-null      float64
 43  YR2003  6 non-null      float64
 44  YR2004  7 non-null      float64
 45  YR2005  8 non-null      float64
 46  YR2006  9 non-null      float64
 47  YR2007  9 non-null      float64
 48  YR2008  9 non-null      float64
 49  YR2009  10 non-null     float64
 50  YR2010  10 non-null     float64
 51  YR2011  10 non-null     float64
 52  YR2012  9 non-null      float64
 53  YR2013  11 non-null     float64
 54  YR2014  11 non-null     float64
 55  YR2015  9 non-null      float64
 56  YR2016  7 non-null      float64
 57  YR2017  2 non-null      float64
 58  YR2018  1 non-null      float64
 59  YR2019  0 non-null      float64
 60  YR2020  0 non-null      float64
dtypes: float64(61)
memory usage: 9.2+ KB

#### Expenditure on tertiary education (% of government expenditure on education)

In [17]:
expenditure_terciary = read_data('SE.XPD.TERT.ZS')
expenditure_terciary

,YR1960,YR1961,YR1962,YR1963,YR1964,YR1965,YR1966,YR1967,YR1968,YR1969,...,YR2011,YR2012,YR2013,YR2014,YR2015,YR2016,YR2017,YR2018,YR2019,YR2020
economy,,,,,,,,,,,,,,,,,,,,,
ARG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,19.43274,19.94066,20.23468,20.40408,20.53570,20.36758,22.08034,NaN,NaN,NaN
AUS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,23.20185,23.67862,25.94840,26.53865,28.85535,26.82461,NaN,NaN,NaN,NaN
BRA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,16.76335,17.30300,18.60182,19.27436,21.45400,NaN,NaN,NaN,NaN,NaN
CAN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,35.59940,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CHN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
DEU,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,28.12803,26.78422,26.48312,26.58781,25.94906,25.98579,NaN,NaN,NaN,NaN
FRA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
GBR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,22.09704,NaN,23.95860,24.32627,22.82077,25.61589,NaN,NaN,NaN,NaN
IDN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,17.17783,16.40550,15.05278,15.80023,NaN,NaN,NaN,NaN,NaN
IND,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,34.68074,32.16690,28.52687,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ITA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,19.35506,19.26296,19.56552,19.58569,18.59916,19.11673,NaN,NaN,NaN,NaN
JPN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,19.99770,20.76276,NaN,19.79765,NaN,NaN,NaN,NaN
KOR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,20.44728,NaN,NaN,NaN,NaN
MEX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,18.12508,19.46464,22.09098,21.32413,21.47549,21.09100,NaN,NaN,NaN,NaN
RUS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,21.15174,21.89587,NaN,21.14236,21.60867,NaN,NaN,NaN,NaN
SAU,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TUR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
USA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,27.22716,27.50228,NaN,NaN,NaN,NaN,NaN,NaN
ZAF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,11.70836,11.91283,12.40889,12.18509,12.54746,NaN,14.36148,15.25153,NaN,NaN

In [18]:
expenditure_terciary.info()

<class 'pandas.core.frame.DataFrame'>
Index: 19 entries, ARG to ZAF
Data columns (total 61 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   YR1960  0 non-null      float64
 1   YR1961  0 non-null      float64
 2   YR1962  0 non-null      float64
 3   YR1963  0 non-null      float64
 4   YR1964  0 non-null      float64
 5   YR1965  0 non-null      float64
 6   YR1966  0 non-null      float64
 7   YR1967  0 non-null      float64
 8   YR1968  0 non-null      float64
 9   YR1969  0 non-null      float64
 10  YR1970  4 non-null      float64
 11  YR1971  6 non-null      float64
 12  YR1972  7 non-null      float64
 13  YR1973  6 non-null      float64
 14  YR1974  6 non-null      float64
 15  YR1975  7 non-null      float64
 16  YR1976  7 non-null      float64
 17  YR1977  6 non-null      float64
 18  YR1978  7 non-null      float64
 19  YR1979  8 non-null      float64
 20  YR1980  7 non-null      float64
 21  YR1981  7 non-null      float64
 22  YR1982  9 non-null      float64
 23  YR1983  10 non-null     float64
 24  YR1984  9 non-null      float64
 25  YR1985  9 non-null      float64
 26  YR1986  9 non-null      float64
 27  YR1987  8 non-null      float64
 28  YR1988  8 non-null      float64
 29  YR1989  9 non-null      float64
 30  YR1990  8 non-null      float64
 31  YR1991  7 non-null      float64
 32  YR1992  7 non-null      float64
 33  YR1993  10 non-null     float64
 34  YR1994  13 non-null     float64
 35  YR1995  13 non-null     float64
 36  YR1996  10 non-null     float64
 37  YR1997  1 non-null      float64
 38  YR1998  10 non-null     float64
 39  YR1999  11 non-null     float64
 40  YR2000  9 non-null      float64
 41  YR2001  8 non-null      float64
 42  YR2002  8 non-null      float64
 43  YR2003  8 non-null      float64
 44  YR2004  9 non-null      float64
 45  YR2005  9 non-null      float64
 46  YR2006  11 non-null     float64
 47  YR2007  10 non-null     float64
 48  YR2008  11 non-null     float64
 49  YR2009  11 non-null     float64
 50  YR2010  11 non-null     float64
 51  YR2011  10 non-null     float64
 52  YR2012  10 non-null     float64
 53  YR2013  13 non-null     float64
 54  YR2014  11 non-null     float64
 55  YR2015  10 non-null     float64
 56  YR2016  9 non-null      float64
 57  YR2017  2 non-null      float64
 58  YR2018  1 non-null      float64
 59  YR2019  0 non-null      float64
 60  YR2020  0 non-null      float64
dtypes: float64(61)
memory usage: 9.2+ KB

#### Government expenditure on education, total (% of government expenditure)

In [19]:
expenditure_total = read_data('SE.XPD.TOTL.GB.ZS')
expenditure_total

,YR1960,YR1961,YR1962,YR1963,YR1964,YR1965,YR1966,YR1967,YR1968,YR1969,...,YR2011,YR2012,YR2013,YR2014,YR2015,YR2016,YR2017,YR2018,YR2019,YR2020
economy,,,,,,,,,,,,,,,,,,,,,
ARG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,15.158560,14.518260,14.457930,13.799330,13.963310,13.355540,13.263920,12.523340,12.53007,NaN
AUS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,13.485000,13.174400,14.041390,13.883790,14.085790,13.804350,13.602920,13.480460,NaN,NaN
BRA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,15.269000,15.727780,15.592710,15.443840,16.218109,15.928830,16.504910,16.148359,NaN,NaN
CAN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,12.219140,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CHN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,13.078100,14.407170,13.315410,12.752610,12.259830,12.269560,12.155300,11.450690,NaN,NaN
DEU,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10.665420,11.034740,10.981110,11.107630,10.999160,10.910540,11.047690,11.230180,NaN,NaN
FRA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,9.652430,9.724830,NaN,NaN
GBR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,12.468570,NaN,12.660240,13.353720,13.490210,13.448640,13.761280,13.344080,NaN,NaN
IDN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,18.006130,18.090420,17.603930,17.671520,20.503300,21.078779,16.110479,20.000000,NaN,17.258051
IND,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,13.564910,13.992120,14.050180,NaN,12.531170,12.753550,NaN,NaN,NaN,NaN
ITA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,8.369560,8.017430,8.132580,7.985930,8.095910,7.774900,8.295180,8.795740,NaN,NaN
JPN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
KOR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
MEX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,18.421021,18.087191,16.905991,18.805941,19.018749,17.939329,17.577299,16.577850,NaN,NaN
RUS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,11.146760,10.861840,11.488520,10.869470,10.985280,13.465080,14.341080,NaN,NaN
SAU,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TUR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.406670,NaN,NaN
USA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ZAF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,18.701559,19.682711,18.696600,18.989161,18.699350,18.048740,18.719290,18.901590,19.59623,19.527281

In [20]:
expenditure_total.info()

<class 'pandas.core.frame.DataFrame'>
Index: 19 entries, ARG to ZAF
Data columns (total 61 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   YR1960  0 non-null      float64
 1   YR1961  0 non-null      float64
 2   YR1962  0 non-null      float64
 3   YR1963  0 non-null      float64
 4   YR1964  0 non-null      float64
 5   YR1965  0 non-null      float64
 6   YR1966  0 non-null      float64
 7   YR1967  0 non-null      float64
 8   YR1968  0 non-null      float64
 9   YR1969  0 non-null      float64
 10  YR1970  0 non-null      float64
 11  YR1971  0 non-null      float64
 12  YR1972  0 non-null      float64
 13  YR1973  0 non-null      float64
 14  YR1974  0 non-null      float64
 15  YR1975  0 non-null      float64
 16  YR1976  0 non-null      float64
 17  YR1977  0 non-null      float64
 18  YR1978  0 non-null      float64
 19  YR1979  0 non-null      float64
 20  YR1980  0 non-null      float64
 21  YR1981  4 non-null      float64
 22  YR1982  4 non-null      float64
 23  YR1983  5 non-null      float64
 24  YR1984  4 non-null      float64
 25  YR1985  4 non-null      float64
 26  YR1986  4 non-null      float64
 27  YR1987  5 non-null      float64
 28  YR1988  6 non-null      float64
 29  YR1989  5 non-null      float64
 30  YR1990  4 non-null      float64
 31  YR1991  6 non-null      float64
 32  YR1992  7 non-null      float64
 33  YR1993  8 non-null      float64
 34  YR1994  11 non-null     float64
 35  YR1995  11 non-null     float64
 36  YR1996  9 non-null      float64
 37  YR1997  3 non-null      float64
 38  YR1998  12 non-null     float64
 39  YR1999  10 non-null     float64
 40  YR2000  11 non-null     float64
 41  YR2001  11 non-null     float64
 42  YR2002  11 non-null     float64
 43  YR2003  10 non-null     float64
 44  YR2004  11 non-null     float64
 45  YR2005  12 non-null     float64
 46  YR2006  12 non-null     float64
 47  YR2007  10 non-null     float64
 48  YR2008  12 non-null     float64
 49  YR2009  11 non-null     float64
 50  YR2010  12 non-null     float64
 51  YR2011  12 non-null     float64
 52  YR2012  11 non-null     float64
 53  YR2013  12 non-null     float64
 54  YR2014  11 non-null     float64
 55  YR2015  12 non-null     float64
 56  YR2016  12 non-null     float64
 57  YR2017  12 non-null     float64
 58  YR2018  13 non-null     float64
 59  YR2019  2 non-null      float64
 60  YR2020  2 non-null      float64
dtypes: float64(61)
memory usage: 9.2+ KB

### Output

#### Literacy rate, adult total (% of people ages 15 and above)

In [21]:
literacy_rate_adult = read_data('SE.ADT.LITR.ZS')
literacy_rate_adult

,YR1960,YR1961,YR1962,YR1963,YR1964,YR1965,YR1966,YR1967,YR1968,YR1969,...,YR2011,YR2012,YR2013,YR2014,YR2015,YR2016,YR2017,YR2018,YR2019,YR2020
economy,,,,,,,,,,,,,,,,,,,,,
ARG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,99.108330,99.105232,99.121948,98.993889,99.179962,99.125008,NaN,99.003868,NaN,NaN
AUS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
BRA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,91.411240,91.337852,91.484238,91.729431,92.047897,92.808441,93.075821,93.227501,NaN,NaN
CAN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CHN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,96.840889,NaN,NaN
DEU,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
FRA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
GBR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
IDN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,92.811913,NaN,NaN,95.116219,95.217934,95.376968,NaN,95.658562,NaN,95.999008
IND,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,69.302559,NaN,NaN,NaN,NaN,NaN,NaN,74.372993,NaN,NaN
ITA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,98.848282,NaN,NaN,NaN,NaN,NaN,NaN,99.155762,NaN,NaN
JPN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
KOR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
MEX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,93.519981,94.228401,93.962852,94.555878,94.472282,94.859619,94.972778,95.379913,NaN,95.247849
RUS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99.730057,NaN,NaN
SAU,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,94.426338,NaN,NaN,NaN,95.328629,NaN,NaN,97.585068
TUR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,94.106087,94.919746,95.256660,95.439629,95.601418,96.167328,96.150528,NaN,96.742210,NaN
USA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ZAF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,93.102142,93.729469,NaN,94.139900,94.367920,NaN,87.046669,NaN,95.022972,NaN

#### Literacy rate, youth total (% of people ages 15-24)

In [23]:
literacy_rate_youth = read_data('SE.ADT.1524.LT.ZS')
literacy_rate_youth

,YR1960,YR1961,YR1962,YR1963,YR1964,YR1965,YR1966,YR1967,YR1968,YR1969,...,YR2011,YR2012,YR2013,YR2014,YR2015,YR2016,YR2017,YR2018,YR2019,YR2020
economy,,,,,,,,,,,,,,,,,,,,,
ARG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,99.628242,99.375870,99.551323,99.296707,99.559700,99.502708,NaN,99.505524,NaN,NaN
AUS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
BRA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,98.486923,98.619659,98.736679,98.845688,98.963753,99.110962,99.155411,99.204170,NaN,NaN
CAN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CHN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99.783600,NaN,NaN
DEU,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
FRA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
GBR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
IDN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,98.778000,NaN,NaN,99.680222,99.670067,99.668808,NaN,99.707077,NaN,99.779510
IND,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,86.144882,NaN,NaN,NaN,NaN,NaN,NaN,91.664040,NaN,NaN
ITA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,99.859642,NaN,NaN,NaN,NaN,NaN,NaN,99.930000,NaN,NaN
JPN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
KOR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
MEX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,98.461769,98.875420,98.564499,99.000038,98.944710,99.116203,99.124687,99.318451,NaN,99.082413
RUS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99.698448,NaN,NaN
SAU,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,99.221771,NaN,NaN,NaN,99.301880,NaN,NaN,99.498413
TUR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,98.709351,99.016022,99.227432,99.358482,99.494392,99.621361,99.750870,NaN,99.907150,NaN
USA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ZAF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,98.789658,98.882042,NaN,98.882278,98.955780,NaN,95.323822,NaN,98.409531,NaN

#### Primary completion rate, total (% of relevant age group)

In [24]:
primary_completion_total = read_data('SE.PRM.CMPT.ZS')
primary_completion_total

,YR1960,YR1961,YR1962,YR1963,YR1964,YR1965,YR1966,YR1967,YR1968,YR1969,...,YR2011,YR2012,YR2013,YR2014,YR2015,YR2016,YR2017,YR2018,YR2019,YR2020
economy,,,,,,,,,,,,,,,,,,,,,
ARG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,103.887711,103.352249,101.645012,103.106438,102.973740,103.893570,99.962761,98.706253,98.547241,NaN
AUS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
BRA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CAN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CHN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
DEU,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,101.566879,98.653137,98.398689,97.282707,98.918297,97.937202,98.805138,100.843323,99.017799,NaN
FRA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
GBR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,102.010498,100.882553,100.122864,100.597458,101.594688,NaN
IDN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,103.098259,101.145630,103.451530,NaN,NaN,100.825920,102.334839,NaN,NaN
IND,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,92.763359,NaN,96.200890,97.571121,97.711319,96.230698,94.373749,NaN,91.661491,94.559128
ITA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,105.363861,101.416191,100.359329,100.112740,99.809547,97.749710,98.816978,97.646721,97.636963,NaN
JPN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
KOR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,102.978081,109.699768,103.185898,96.155319,101.410797,98.015572,91.355118,95.376770,105.239731,NaN
MEX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,100.197533,106.011009,109.425041,110.508842,104.909821,103.969391,104.097839,102.255890,102.465538,NaN
RUS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,97.113358,97.717690,100.108002,99.934029,100.297852,96.142929,NaN,101.963211,105.225853,NaN
SAU,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,101.652786,107.159813,110.964279,NaN,NaN,NaN,103.334740,96.706062,96.228813,99.327309
TUR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,101.248238,99.819923,NaN,91.397820,92.233093,NaN,89.748901,88.527779,90.846771,NaN
USA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,98.832199,100.092697,100.489052,NaN
ZAF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,90.110489,87.255333,NaN,90.344498,91.999489,NaN

### Output-negative

#### Lower secondary completion rate, total (% of relevant age group)

In [25]:
lower_secondary_completion = read_data('SE.SEC.CMPT.LO.ZS')
lower_secondary_completion

,YR1960,YR1961,YR1962,YR1963,YR1964,YR1965,YR1966,YR1967,YR1968,YR1969,...,YR2011,YR2012,YR2013,YR2014,YR2015,YR2016,YR2017,YR2018,YR2019,YR2020
economy,,,,,,,,,,,,,,,,,,,,,
ARG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,85.269440,86.210251,88.456207,88.916321,90.115860,89.205307,89.817039,90.867340,93.539200,NaN
AUS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
BRA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,71.750122,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CAN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CHN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,99.515488,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
DEU,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
FRA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,97.198540,98.715881,97.295433,97.228271,96.091057,98.452850,99.649277,99.344040,99.455688,NaN
GBR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,100.895210,101.393990,99.953957,NaN
IDN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,89.239868,82.652313,81.364311,NaN,91.583359,93.853691,89.971764,NaN,NaN,NaN
IND,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,76.274239,NaN,80.784973,85.504082,85.433502,85.855850,84.999443,NaN,83.223412,84.582222
ITA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,103.970734,103.020897,103.284157,103.729317,99.970757,98.889412,98.974533,98.959923,97.539108,NaN
JPN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
KOR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,98.873932,NaN,99.155037,101.474960,109.151283,103.278732,95.770897,100.073174,96.704659,NaN
MEX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,85.355820,85.377213,86.934090,87.267258,92.964333,96.015518,97.190300,91.486656,90.688133,NaN
RUS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,86.110641,86.635521,91.086098,96.000130,95.439331,95.931252,NaN,103.404991,103.989319,NaN
SAU,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,99.665482,NaN,NaN,NaN,NaN,104.576241,106.478569,104.640388,105.457581,104.118401
TUR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,96.110748,95.321228,94.672333,96.867661,94.906158,NaN,87.506119,86.522949,88.789009,NaN
USA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,104.852257,103.384171,103.408463,NaN
ZAF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,80.768852,NaN,80.033234,80.372330,NaN

#### Adolescents out of school (% of lower secondary school age)

In [26]:
adolescents_out_of_school = read_data('SE.SEC.UNER.LO.ZS')
adolescents_out_of_school

,YR1960,YR1961,YR1962,YR1963,YR1964,YR1965,YR1966,YR1967,YR1968,YR1969,...,YR2011,YR2012,YR2013,YR2014,YR2015,YR2016,YR2017,YR2018,YR2019,YR2020
economy,,,,,,,,,,,,,,,,,,,,,
ARG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.98483,1.11118,0.77256,0.51128,0.38344,0.12941,0.007790,0.11445,0.93901,NaN
AUS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.61647,0.42192,0.16973,1.09826,1.882770,2.45424,1.97147,NaN
BRA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.36431,5.60056,4.49730,5.18532,4.43386,3.18607,4.464150,2.43722,2.35421,NaN
CAN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.30094,0.48872,0.28736,0.07248,NaN,NaN,NaN,NaN,NaN
CHN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
DEU,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.35749,2.13488,3.13701,4.26125,4.68140,4.64572,4.715850,4.67297,4.30337,NaN
FRA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.58435,1.68750,1.80315,2.53989,2.01316,1.55782,1.152300,0.95938,0.46203,NaN
GBR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.62989,6.02610,3.33517,3.46450,1.82057,NaN,0.127790,0.12270,0.16207,NaN
IDN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,15.27848,14.53837,13.66343,13.44958,NaN,NaN,NaN,16.33552,NaN,NaN
IND,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,14.87672,NaN,NaN,NaN,NaN,NaN,NaN,15.12684
ITA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.37408,0.20386,0.10082,0.20825,0.41663,1.02070,1.657510,2.05278,2.44502,NaN
JPN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.26323,0.281530,0.38521,NaN,NaN
KOR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.08803,0.02664,0.29235,NaN,0.23639,3.75374,5.631600,2.74639,4.86950,NaN
MEX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,7.20105,6.90474,4.32491,3.24374,2.42849,3.38830,5.939560,7.78914,7.64868,NaN
RUS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,2.88641,1.88252,0.48141,0.64116,0.162810,0.21617,0.23829,NaN
SAU,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,3.07061,NaN,1.43610,1.04733,1.62103
TUR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.20498,0.96928,3.18261,5.48738,8.00510,9.79805,8.914180,6.21765,3.48943,NaN
USA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ZAF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,19.139099,14.36363,10.32395,NaN

In [27]:
adolescents_out_of_school.info()

<class 'pandas.core.frame.DataFrame'>
Index: 19 entries, ARG to ZAF
Data columns (total 61 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   YR1960  0 non-null      float64
 1   YR1961  0 non-null      float64
 2   YR1962  0 non-null      float64
 3   YR1963  0 non-null      float64
 4   YR1964  0 non-null      float64
 5   YR1965  0 non-null      float64
 6   YR1966  0 non-null      float64
 7   YR1967  0 non-null      float64
 8   YR1968  0 non-null      float64
 9   YR1969  0 non-null      float64
 10  YR1970  0 non-null      float64
 11  YR1971  2 non-null      float64
 12  YR1972  3 non-null      float64
 13  YR1973  2 non-null      float64
 14  YR1974  5 non-null      float64
 15  YR1975  4 non-null      float64
 16  YR1976  4 non-null      float64
 17  YR1977  3 non-null      float64
 18  YR1978  3 non-null      float64
 19  YR1979  3 non-null      float64
 20  YR1980  1 non-null      float64
 21  YR1981  2 non-null      float64
 22  YR1982  1 non-null      float64
 23  YR1983  0 non-null      float64
 24  YR1984  1 non-null      float64
 25  YR1985  1 non-null      float64
 26  YR1986  4 non-null      float64
 27  YR1987  3 non-null      float64
 28  YR1988  2 non-null      float64
 29  YR1989  3 non-null      float64
 30  YR1990  2 non-null      float64
 31  YR1991  3 non-null      float64
 32  YR1992  2 non-null      float64
 33  YR1993  2 non-null      float64
 34  YR1994  5 non-null      float64
 35  YR1995  4 non-null      float64
 36  YR1996  4 non-null      float64
 37  YR1997  2 non-null      float64
 38  YR1998  3 non-null      float64
 39  YR1999  9 non-null      float64
 40  YR2000  8 non-null      float64
 41  YR2001  8 non-null      float64
 42  YR2002  10 non-null     float64
 43  YR2003  10 non-null     float64
 44  YR2004  10 non-null     float64
 45  YR2005  10 non-null     float64
 46  YR2006  9 non-null      float64
 47  YR2007  10 non-null     float64
 48  YR2008  9 non-null      float64
 49  YR2009  11 non-null     float64
 50  YR2010  9 non-null      float64
 51  YR2011  10 non-null     float64
 52  YR2012  11 non-null     float64
 53  YR2013  14 non-null     float64
 54  YR2014  12 non-null     float64
 55  YR2015  12 non-null     float64
 56  YR2016  12 non-null     float64
 57  YR2017  13 non-null     float64
 58  YR2018  15 non-null     float64
 59  YR2019  13 non-null     float64
 60  YR2020  2 non-null      float64
dtypes: float64(61)
memory usage: 9.2+ KB

#### Children out of school (% of primary school age)

In [28]:
children_out_school = read_data('SE.PRM.UNER.ZS')
children_out_school

,YR1960,YR1961,YR1962,YR1963,YR1964,YR1965,YR1966,YR1967,YR1968,YR1969,...,YR2011,YR2012,YR2013,YR2014,YR2015,YR2016,YR2017,YR2018,YR2019,YR2020
economy,,,,,,,,,,,,,,,,,,,,,
ARG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.56590,0.57176,0.40809,0.09804,0.05630,0.45239,0.43269,0.40345,0.42247,NaN
AUS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.32234,2.01349,0.06038,0.08473,0.08832,0.04413,0.31825,0.42838,0.68465,NaN
BRA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.99311,2.19181,0.45904,0.13608,0.71881,0.83841,0.39079,0.51906,0.57306,NaN
CAN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.54833,0.56769,0.60887,0.41093,0.04413,0.11750,0.21191,0.27903,NaN
CHN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
DEU,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.45141,3.29518,3.58947,3.23601,1.85685,0.51429,0.52930,0.68894,0.98669,NaN
FRA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.24182,0.36989,0.57923,1.36188,0.51498,0.16720,0.05840,0.01472,0.00540,NaN
GBR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.66501,1.50386,0.27542,0.10052,0.06567,0.34792,0.43037,0.66309,1.13423,NaN
IDN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.16939,4.05297,6.27357,6.82466,NaN,6.37853,5.06120,5.62332,NaN,NaN
IND,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.28239,3.01236,2.26232,NaN,NaN,NaN,NaN,NaN,NaN,5.37329
ITA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.48066,0.26234,0.11543,0.83955,1.47977,2.04650,2.52176,3.14660,3.49892,NaN
JPN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1.75722,2.28951,2.41312,NaN,NaN
KOR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.31767,2.02933,4.51018,4.06879,1.43787,2.71083,2.42258,0.92399,0.00993,NaN
MEX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.26297,0.33020,0.40370,0.49922,0.57450,0.65455,0.72876,0.69946,0.79265,NaN
RUS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.41207,0.45141,0.40546,2.55306,1.33646,0.59348,0.13300,0.16377,0.07131,NaN
SAU,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.87166,0.14801,2.16750,NaN,0.69715,1.84649,NaN,NaN,NaN,5.17592
TUR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.78723,6.19880,6.56701,5.28857,5.26441,5.85389,5.12310,4.95620,4.78203,NaN
USA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,2.89807,NaN,1.80586,0.35997,0.42438,0.57421,0.91657,NaN
ZAF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,4.35449,NaN,7.55062,11.00796,10.78704,NaN

In [29]:
children_out_school.info()

<class 'pandas.core.frame.DataFrame'>
Index: 19 entries, ARG to ZAF
Data columns (total 61 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   YR1960  0 non-null      float64
 1   YR1961  0 non-null      float64
 2   YR1962  0 non-null      float64
 3   YR1963  0 non-null      float64
 4   YR1964  0 non-null      float64
 5   YR1965  0 non-null      float64
 6   YR1966  0 non-null      float64
 7   YR1967  0 non-null      float64
 8   YR1968  0 non-null      float64
 9   YR1969  0 non-null      float64
 10  YR1970  2 non-null      float64
 11  YR1971  8 non-null      float64
 12  YR1972  5 non-null      float64
 13  YR1973  6 non-null      float64
 14  YR1974  8 non-null      float64
 15  YR1975  6 non-null      float64
 16  YR1976  7 non-null      float64
 17  YR1977  7 non-null      float64
 18  YR1978  5 non-null      float64
 19  YR1979  7 non-null      float64
 20  YR1980  5 non-null      float64
 21  YR1981  6 non-null      float64
 22  YR1982  7 non-null      float64
 23  YR1983  7 non-null      float64
 24  YR1984  6 non-null      float64
 25  YR1985  10 non-null     float64
 26  YR1986  9 non-null      float64
 27  YR1987  11 non-null     float64
 28  YR1988  10 non-null     float64
 29  YR1989  10 non-null     float64
 30  YR1990  11 non-null     float64
 31  YR1991  12 non-null     float64
 32  YR1992  10 non-null     float64
 33  YR1993  8 non-null      float64
 34  YR1994  11 non-null     float64
 35  YR1995  12 non-null     float64
 36  YR1996  8 non-null      float64
 37  YR1997  9 non-null      float64
 38  YR1998  8 non-null      float64
 39  YR1999  12 non-null     float64
 40  YR2000  12 non-null     float64
 41  YR2001  12 non-null     float64
 42  YR2002  12 non-null     float64
 43  YR2003  13 non-null     float64
 44  YR2004  12 non-null     float64
 45  YR2005  13 non-null     float64
 46  YR2006  11 non-null     float64
 47  YR2007  13 non-null     float64
 48  YR2008  12 non-null     float64
 49  YR2009  14 non-null     float64
 50  YR2010  12 non-null     float64
 51  YR2011  14 non-null     float64
 52  YR2012  15 non-null     float64
 53  YR2013  16 non-null     float64
 54  YR2014  13 non-null     float64
 55  YR2015  15 non-null     float64
 56  YR2016  16 non-null     float64
 57  YR2017  16 non-null     float64
 58  YR2018  16 non-null     float64
 59  YR2019  14 non-null     float64
 60  YR2020  2 non-null      float64
dtypes: float64(61)
memory usage: 9.2+ KB

## Mudancas climaticas e meio ambiente

### Input

### Output

#### Access to electricity (% of population)

In [39]:
access_electricity = read_data('EG.ELC.ACCS.ZS')
access_electricity

,YR1960,YR1961,YR1962,YR1963,YR1964,YR1965,YR1966,YR1967,YR1968,YR1969,...,YR2011,YR2012,YR2013,YR2014,YR2015,YR2016,YR2017,YR2018,YR2019,YR2020
economy,,,,,,,,,,,,,,,,,,,,,
ARG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,99.080200,99.228859,99.356224,100.000000,99.811684,99.956017,100.000000,100.000000,100.000000,NaN
AUS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,NaN
BRA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,99.328691,99.519494,99.575151,99.650247,99.710902,99.700000,99.800000,99.700000,99.800000,NaN
CAN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,NaN
CHN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,99.857224,99.964874,99.997009,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,NaN
DEU,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,NaN
FRA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,NaN
GBR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,NaN
IDN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,94.830000,96.000000,96.464258,97.010000,97.537367,97.620000,98.140000,98.510000,98.850000,NaN
IND,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,67.600000,79.900000,80.738045,83.585213,88.000000,89.534882,92.456833,95.193298,97.815285,NaN
ITA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,NaN
JPN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,NaN
KOR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,NaN
MEX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,99.064095,99.111637,99.232025,99.172928,99.000000,99.500000,100.000000,99.500000,100.000000,NaN
RUS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,100.000000,100.000000,100.000000,100.000000,95.500000,100.000000,100.000000,100.000000,100.000000,NaN
SAU,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,100.000000,100.000000,100.000000,100.000000,100.000000,99.900000,99.930000,100.000000,100.000000,NaN
TUR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,NaN
USA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,NaN
ZAF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,83.600000,85.300000,85.200000,86.000000,85.300000,84.200000,84.400000,84.700000,85.000000,NaN

In [40]:
access_electricity.info()

<class 'pandas.core.frame.DataFrame'>
Index: 19 entries, ARG to ZAF
Data columns (total 61 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   YR1960  0 non-null      float64
 1   YR1961  0 non-null      float64
 2   YR1962  0 non-null      float64
 3   YR1963  0 non-null      float64
 4   YR1964  0 non-null      float64
 5   YR1965  0 non-null      float64
 6   YR1966  0 non-null      float64
 7   YR1967  0 non-null      float64
 8   YR1968  0 non-null      float64
 9   YR1969  0 non-null      float64
 10  YR1970  0 non-null      float64
 11  YR1971  0 non-null      float64
 12  YR1972  0 non-null      float64
 13  YR1973  0 non-null      float64
 14  YR1974  0 non-null      float64
 15  YR1975  0 non-null      float64
 16  YR1976  0 non-null      float64
 17  YR1977  0 non-null      float64
 18  YR1978  0 non-null      float64
 19  YR1979  0 non-null      float64
 20  YR1980  0 non-null      float64
 21  YR1981  0 non-null      float64
 22  YR1982  0 non-null      float64
 23  YR1983  0 non-null      float64
 24  YR1984  0 non-null      float64
 25  YR1985  0 non-null      float64
 26  YR1986  0 non-null      float64
 27  YR1987  0 non-null      float64
 28  YR1988  0 non-null      float64
 29  YR1989  0 non-null      float64
 30  YR1990  13 non-null     float64
 31  YR1991  14 non-null     float64
 32  YR1992  15 non-null     float64
 33  YR1993  16 non-null     float64
 34  YR1994  16 non-null     float64
 35  YR1995  16 non-null     float64
 36  YR1996  17 non-null     float64
 37  YR1997  17 non-null     float64
 38  YR1998  17 non-null     float64
 39  YR1999  17 non-null     float64
 40  YR2000  18 non-null     float64
 41  YR2001  18 non-null     float64
 42  YR2002  18 non-null     float64
 43  YR2003  18 non-null     float64
 44  YR2004  18 non-null     float64
 45  YR2005  18 non-null     float64
 46  YR2006  18 non-null     float64
 47  YR2007  18 non-null     float64
 48  YR2008  18 non-null     float64
 49  YR2009  18 non-null     float64
 50  YR2010  19 non-null     float64
 51  YR2011  19 non-null     float64
 52  YR2012  19 non-null     float64
 53  YR2013  19 non-null     float64
 54  YR2014  19 non-null     float64
 55  YR2015  19 non-null     float64
 56  YR2016  19 non-null     float64
 57  YR2017  19 non-null     float64
 58  YR2018  19 non-null     float64
 59  YR2019  19 non-null     float64
 60  YR2020  0 non-null      float64
dtypes: float64(61)
memory usage: 9.2+ KB

In [41]:
access_electricity.drop(access_electricity.loc[:, :'YR1989'], axis = 1, inplace=True)
access_electricity.drop(['YR2020'], axis = 1, inplace=True)
access_electricity.fillna(access_electricity.mean(), inplace=True)

In [42]:
access_electricity

,YR1990,YR1991,YR1992,YR1993,YR1994,YR1995,YR1996,YR1997,YR1998,YR1999,...,YR2010,YR2011,YR2012,YR2013,YR2014,YR2015,YR2016,YR2017,YR2018,YR2019
economy,,,,,,,,,,,,,,,,,,,,,
ARG,92.154800,92.492188,92.829453,93.166046,93.501274,93.834465,94.164940,94.492012,94.815002,95.133156,...,98.820000,99.080200,99.228859,99.356224,100.000000,99.811684,99.956017,100.000000,100.000000,100.000000
AUS,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,...,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000
BRA,87.475116,90.606544,88.803833,89.999927,91.883728,91.728598,92.867095,93.354139,94.193812,94.762960,...,99.352173,99.328691,99.519494,99.575151,99.650247,99.710902,99.700000,99.800000,99.700000,99.800000
CAN,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,...,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000
CHN,98.424058,95.136529,96.094536,92.807117,93.326483,93.732894,92.124658,93.444350,93.360218,94.223894,...,99.700000,99.857224,99.964874,99.997009,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000
DEU,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,...,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000
FRA,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,...,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000
GBR,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,...,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000
IDN,98.424058,48.900000,66.696564,55.430000,62.800000,66.860000,72.390000,80.300000,80.940000,83.730000,...,94.150000,94.830000,96.000000,96.464258,97.010000,97.537367,97.620000,98.140000,98.510000,98.850000
IND,98.424058,95.136529,96.094536,50.900000,49.811310,51.408775,53.003521,54.594864,56.182133,60.100000,...,76.300000,67.600000,79.900000,80.738045,83.585213,88.000000,89.534882,92.456833,95.193298,97.815285
ITA,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,...,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000
JPN,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,...,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000
KOR,99.882843,99.912674,99.942215,99.969437,99.989120,100.000000,100.000000,100.000000,100.000000,100.000000,...,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000
MEX,98.424058,95.136529,93.145981,95.448463,95.238294,95.894463,96.093624,96.329582,96.092755,96.748299,...,99.236696,99.064095,99.111637,99.232025,99.172928,99.000000,99.500000,100.000000,99.500000,100.000000
RUS,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,...,100.000000,100.000000,100.000000,100.000000,100.000000,95.500000,100.000000,100.000000,100.000000,100.000000
SAU,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,...,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,99.900000,99.930000,100.000000,100.000000
TUR,98.424058,95.136529,96.094536,92.807117,93.326483,93.732894,92.124658,93.444350,93.360218,94.223894,...,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000
USA,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,...,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000
ZAF,98.424058,95.136529,96.094536,92.807117,93.326483,93.732894,57.600000,69.483353,64.900000,71.331787,...,82.900000,83.600000,85.300000,85.200000,86.000000,85.300000,84.200000,84.400000,84.700000,85.000000

#### Electricity production from hydroelectric sources (% of total)

In [43]:
electricity_production_hydroelectric = read_data('EG.ELC.HYRO.ZS')
electricity_production_hydroelectric

,YR1960,YR1961,YR1962,YR1963,YR1964,YR1965,YR1966,YR1967,YR1968,YR1969,...,YR2011,YR2012,YR2013,YR2014,YR2015,YR2016,YR2017,YR2018,YR2019,YR2020
economy,,,,,,,,,,,,,,,,,,,,,
ARG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,30.642584,27.232041,29.369131,29.607940,26.241575,NaN,NaN,NaN,NaN,NaN
AUS,18.639564,20.040767,20.029329,24.096254,22.480773,24.784077,19.635312,19.582252,18.215124,18.356831,...,6.599267,5.585644,7.279436,7.405826,5.296184,NaN,NaN,NaN,NaN,NaN
BRA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,80.550515,75.158155,68.463446,63.224984,61.848494,NaN,NaN,NaN,NaN,NaN
CAN,92.089061,90.910274,87.968457,84.178603,83.157818,80.221191,81.224191,79.196703,75.455810,77.082651,...,59.040234,59.723302,58.888079,57.254617,56.744193,NaN,NaN,NaN,NaN,NaN
CHN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,14.624130,17.308734,16.731349,18.552494,19.069813,NaN,NaN,NaN,NaN,NaN
DEU,10.192345,9.436815,8.309111,7.499967,6.771992,8.319286,8.945965,8.346234,7.727279,5.839527,...,2.910110,3.487954,3.633491,3.149349,2.960683,NaN,NaN,NaN,NaN,NaN
FRA,54.473148,48.467778,41.605664,47.702146,35.648819,44.172525,47.103679,38.814743,40.896038,38.502328,...,8.050506,10.484644,12.468703,11.261935,9.661150,NaN,NaN,NaN,NaN,NaN
GBR,2.273186,2.626573,2.339886,1.893450,1.957422,2.132291,1.990989,2.110355,1.597811,1.348460,...,1.560624,1.468100,1.323307,1.757567,1.869745,NaN,NaN,NaN,NaN,NaN
IDN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6.770910,6.398540,7.833997,6.653619,5.872624,NaN,NaN,NaN,NaN,NaN
IND,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,13.362233,11.089365,12.388661,11.080157,9.982039,NaN,NaN,NaN,NaN,NaN
ITA,81.900339,69.190085,60.354095,64.467941,51.104179,51.618762,48.908180,44.003326,41.349275,37.556107,...,15.241412,14.085194,18.330097,21.050569,16.173347,NaN,NaN,NaN,NaN,NaN
JPN,50.649351,51.476154,44.444444,43.114334,38.339745,39.667310,36.932744,28.123077,27.008641,23.954856,...,7.743628,7.144020,7.370949,7.758890,8.229093,NaN,NaN,NaN,NaN,NaN
KOR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.884141,0.747549,0.797373,0.504153,0.390732,NaN,NaN,NaN,NaN,NaN
MEX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,11.972545,10.377635,9.417945,12.900005,9.903965,NaN,NaN,NaN,NaN,NaN
RUS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,15.749653,15.514447,17.128677,16.498311,15.764769,NaN,NaN,NaN,NaN,NaN
SAU,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN
TUR,35.595027,42.012620,31.573034,52.824504,37.025388,43.993539,42.118537,38.351312,45.775663,43.952539,...,22.815866,24.161155,24.742457,16.131337,25.649488,NaN,NaN,NaN,NaN,NaN
USA,18.439899,18.271231,18.880885,17.255415,17.160152,17.524137,16.249088,17.447887,15.929241,16.530809,...,7.436102,6.521156,6.317910,6.053798,5.841638,NaN,NaN,NaN,NaN,NaN
ZAF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.792446,0.472710,0.457755,0.390827,0.324638,NaN,NaN,NaN,NaN,NaN

In [46]:
electricity_production_hydroelectric.loc[:, 'YR1971':]

,YR1971,YR1972,YR1973,YR1974,YR1975,YR1976,YR1977,YR1978,YR1979,YR1980,...,YR2011,YR2012,YR2013,YR2014,YR2015,YR2016,YR2017,YR2018,YR2019,YR2020
economy,,,,,,,,,,,,,,,,,,,,,
ARG,6.535726,5.943255,11.229886,17.989267,17.724841,16.590548,17.789159,23.185978,28.320183,38.140331,...,30.642584,27.232041,29.369131,29.607940,26.241575,NaN,NaN,NaN,NaN,NaN
AUS,21.832406,20.821114,17.715918,18.964700,19.956781,19.720651,15.938269,16.180619,16.955529,13.589684,...,6.599267,5.585644,7.279436,7.405826,5.296184,NaN,NaN,NaN,NaN,NaN
BRA,83.754702,88.671356,89.438556,91.603788,91.577881,92.091789,92.543460,91.144249,91.958919,92.486009,...,80.550515,75.158155,68.463446,63.224984,61.848494,NaN,NaN,NaN,NaN,NaN
CAN,73.235722,73.798892,72.072452,74.305416,73.072759,71.319496,68.363114,68.605774,67.979449,67.281758,...,59.040234,59.723302,58.888079,57.254617,56.744193,NaN,NaN,NaN,NaN,NaN
CHN,21.573111,22.127493,22.526661,25.211217,22.695179,22.097306,21.034397,17.384390,17.769108,19.362672,...,14.624130,17.308734,16.731349,18.552494,19.069813,NaN,NaN,NaN,NaN,NaN
DEU,4.111548,3.816052,4.069165,4.516557,4.443547,3.286010,4.124604,4.098006,3.930295,4.089077,...,2.910110,3.487954,3.633491,3.149349,2.960683,NaN,NaN,NaN,NaN,NaN
FRA,31.342517,28.517357,26.129266,30.089860,32.436021,23.584333,36.261345,30.223087,27.613954,27.016649,...,8.050506,10.484644,12.468703,11.261935,9.661150,NaN,NaN,NaN,NaN,NaN
GBR,1.312970,1.290497,1.371236,1.492647,1.385206,1.339732,1.373656,1.394600,1.421420,1.369728,...,1.560624,1.468100,1.323307,1.757567,1.869745,NaN,NaN,NaN,NaN,NaN
IDN,44.020501,33.049574,43.459916,41.581148,39.899666,42.823529,35.873426,28.193115,23.125302,17.928552,...,6.770910,6.398540,7.833997,6.653619,5.872624,NaN,NaN,NaN,NaN,NaN
IND,42.224030,38.577061,39.808506,36.362451,38.767079,36.441981,38.430980,42.833404,40.322280,38.665714,...,13.362233,11.089365,12.388661,11.080157,9.982039,NaN,NaN,NaN,NaN,NaN
ITA,31.535668,30.881145,26.072848,25.650474,28.139363,24.215152,31.001225,26.277301,25.668858,24.659625,...,15.241412,14.085194,18.330097,21.050569,16.173347,NaN,NaN,NaN,NaN,NaN
JPN,21.990076,19.990604,14.348918,18.092854,17.627963,16.487440,13.783906,12.558357,13.794205,15.421348,...,7.743628,7.144020,7.370949,7.758890,8.229093,NaN,NaN,NaN,NaN,NaN
KOR,12.523719,11.546583,8.661046,11.321651,8.364811,7.738893,5.239403,5.737861,6.539326,5.327748,...,0.884141,0.747549,0.797373,0.504153,0.390732,NaN,NaN,NaN,NaN,NaN
MEX,46.332034,44.679860,43.636119,40.769569,34.450414,36.190136,36.724775,28.517284,28.966739,25.217287,...,11.972545,10.377635,9.417945,12.900005,9.903965,NaN,NaN,NaN,NaN,NaN
RUS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,15.749653,15.514447,17.128677,16.498311,15.764769,NaN,NaN,NaN,NaN,NaN
SAU,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN
TUR,26.684388,28.506626,20.949698,24.901684,37.790437,45.807581,41.682470,42.966952,45.684220,48.756176,...,22.815866,24.161155,24.742457,16.131337,25.649488,NaN,NaN,NaN,NaN,NaN
USA,15.468891,14.639224,13.502050,15.535051,15.069761,13.402655,9.972837,12.226639,11.975481,11.485136,...,7.436102,6.521156,6.317910,6.053798,5.841638,NaN,NaN,NaN,NaN,NaN
ZAF,0.204952,1.401257,1.529741,1.625456,1.495447,2.363971,2.420228,2.256912,1.274680,1.002516,...,0.792446,0.472710,0.457755,0.390827,0.324638,NaN,NaN,NaN,NaN,NaN

In [44]:
electricity_production_hydroelectric.info()

<class 'pandas.core.frame.DataFrame'>
Index: 19 entries, ARG to ZAF
Data columns (total 61 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   YR1960  9 non-null      float64
 1   YR1961  9 non-null      float64
 2   YR1962  9 non-null      float64
 3   YR1963  9 non-null      float64
 4   YR1964  9 non-null      float64
 5   YR1965  9 non-null      float64
 6   YR1966  9 non-null      float64
 7   YR1967  9 non-null      float64
 8   YR1968  9 non-null      float64
 9   YR1969  9 non-null      float64
 10  YR1970  9 non-null      float64
 11  YR1971  18 non-null     float64
 12  YR1972  18 non-null     float64
 13  YR1973  18 non-null     float64
 14  YR1974  18 non-null     float64
 15  YR1975  18 non-null     float64
 16  YR1976  18 non-null     float64
 17  YR1977  18 non-null     float64
 18  YR1978  18 non-null     float64
 19  YR1979  18 non-null     float64
 20  YR1980  18 non-null     float64
 21  YR1981  18 non-null     float64
 22  YR1982  18 non-null     float64
 23  YR1983  18 non-null     float64
 24  YR1984  18 non-null     float64
 25  YR1985  18 non-null     float64
 26  YR1986  18 non-null     float64
 27  YR1987  18 non-null     float64
 28  YR1988  18 non-null     float64
 29  YR1989  18 non-null     float64
 30  YR1990  19 non-null     float64
 31  YR1991  19 non-null     float64
 32  YR1992  19 non-null     float64
 33  YR1993  19 non-null     float64
 34  YR1994  19 non-null     float64
 35  YR1995  19 non-null     float64
 36  YR1996  19 non-null     float64
 37  YR1997  19 non-null     float64
 38  YR1998  19 non-null     float64
 39  YR1999  19 non-null     float64
 40  YR2000  19 non-null     float64
 41  YR2001  19 non-null     float64
 42  YR2002  19 non-null     float64
 43  YR2003  19 non-null     float64
 44  YR2004  19 non-null     float64
 45  YR2005  19 non-null     float64
 46  YR2006  19 non-null     float64
 47  YR2007  19 non-null     float64
 48  YR2008  19 non-null     float64
 49  YR2009  19 non-null     float64
 50  YR2010  19 non-null     float64
 51  YR2011  19 non-null     float64
 52  YR2012  19 non-null     float64
 53  YR2013  19 non-null     float64
 54  YR2014  19 non-null     float64
 55  YR2015  19 non-null     float64
 56  YR2016  0 non-null      float64
 57  YR2017  0 non-null      float64
 58  YR2018  0 non-null      float64
 59  YR2019  0 non-null      float64
 60  YR2020  0 non-null      float64
dtypes: float64(61)
memory usage: 9.2+ KB

In [47]:
electricity_production_hydroelectric.drop(electricity_production_hydroelectric.loc[:, :'YR1970'], axis = 1, inplace=True)
electricity_production_hydroelectric.drop(electricity_production_hydroelectric.loc[:, 'YR2016':], axis = 1, inplace=True)

#### Electricity production from renewable sources, excluding hydroelectric (% of total)

In [49]:
electricity_production_renewable = read_data('EG.ELC.RNWX.ZS')
electricity_production_renewable

,YR1960,YR1961,YR1962,YR1963,YR1964,YR1965,YR1966,YR1967,YR1968,YR1969,...,YR2011,YR2012,YR2013,YR2014,YR2015,YR2016,YR2017,YR2018,YR2019,YR2020
economy,,,,,,,,,,,,,,,,,,,,,
ARG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.663386,2.029095,2.115360,1.968265,1.898494,NaN,NaN,NaN,NaN,NaN
AUS,1.412653,1.314078,1.201678,1.099102,0.949846,0.884612,0.789415,0.745061,0.675255,0.616133,...,3.827386,5.007009,5.984673,7.500886,8.341658,NaN,NaN,NaN,NaN,NaN
BRA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6.570482,7.290129,8.225762,9.857090,12.118414,NaN,NaN,NaN,NaN,NaN
CAN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,3.298016,3.507259,4.409954,5.570376,6.267257,NaN,NaN,NaN,NaN,NaN
CHN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.137640,2.657515,3.564878,4.056660,4.857004,NaN,NaN,NaN,NaN,NaN
DEU,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,17.473173,19.512504,20.439059,22.980747,26.271087,NaN,NaN,NaN,NaN,NaN
FRA,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.351944,0.517598,0.751160,0.776113,...,3.524242,4.342710,4.576583,5.193969,6.196517,NaN,NaN,NaN,NaN,NaN
GBR,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,7.928430,9.955860,13.665173,17.505286,22.970305,NaN,NaN,NaN,NaN,NaN
IDN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5.221981,4.838274,4.436163,4.821482,4.778532,NaN,NaN,NaN,NaN,NaN
IND,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.954730,4.643609,4.960653,5.173683,5.361011,NaN,NaN,NaN,NaN,NaN
ITA,3.772102,3.831551,3.658669,3.594458,3.457360,3.239945,3.748658,3.611515,3.504471,3.477721,...,12.353317,16.935196,20.575251,22.341038,22.505878,NaN,NaN,NaN,NaN,NaN
JPN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,3.719216,4.050228,4.834342,6.300470,7.755688,NaN,NaN,NaN,NaN,NaN
KOR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.553982,0.588396,0.835485,1.062715,1.503935,NaN,NaN,NaN,NaN,NaN
MEX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.916258,3.410496,3.881598,4.643511,5.490168,NaN,NaN,NaN,NaN,NaN
RUS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.053371,0.049284,0.045954,0.069940,0.091027,NaN,NaN,NaN,NaN,NaN
SAU,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000000,0.000368,0.000352,0.000321,0.000296,NaN,NaN,NaN,NaN,NaN
TUR,1.456483,1.461309,1.264045,1.581722,2.179286,2.018978,2.197802,2.785381,2.580738,2.270987,...,2.510975,3.069362,4.080715,4.755857,6.307132,NaN,NaN,NaN,NaN,NaN
USA,0.015256,0.021542,0.022787,0.029435,0.030717,0.030856,0.031599,0.036885,0.044686,0.052309,...,4.789611,5.486241,6.320009,6.900029,7.386955,NaN,NaN,NaN,NaN,NaN
ZAF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.125975,0.130241,0.151269,0.902309,1.930403,NaN,NaN,NaN,NaN,NaN

In [51]:
electricity_production_renewable.loc[:, 'YR1971':]

,YR1971,YR1972,YR1973,YR1974,YR1975,YR1976,YR1977,YR1978,YR1979,YR1980,...,YR2011,YR2012,YR2013,YR2014,YR2015,YR2016,YR2017,YR2018,YR2019,YR2020
economy,,,,,,,,,,,,,,,,,,,,,
ARG,0.241280,0.292421,0.213795,0.207513,0.211294,0.188642,0.188196,0.182449,0.247071,0.241777,...,1.663386,2.029095,2.115360,1.968265,1.898494,NaN,NaN,NaN,NaN,NaN
AUS,0.495805,0.503751,0.524755,0.616353,0.664592,0.633574,0.520082,0.472061,0.461150,0.404267,...,3.827386,5.007009,5.984673,7.500886,8.341658,NaN,NaN,NaN,NaN,NaN
BRA,1.198185,1.243964,1.158731,1.094855,1.097105,0.959648,1.105809,1.181595,1.400129,1.295021,...,6.570482,7.290129,8.225762,9.857090,12.118414,NaN,NaN,NaN,NaN,NaN
CAN,0.000000,0.000000,0.000000,0.000000,0.000000,0.237073,0.331961,0.330119,0.374537,0.348266,...,3.298016,3.507259,4.409954,5.570376,6.267257,NaN,NaN,NaN,NaN,NaN
CHN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,2.137640,2.657515,3.564878,4.056660,4.857004,NaN,NaN,NaN,NaN,NaN
DEU,0.845839,0.814442,0.777878,0.267819,0.287412,0.296851,0.286584,0.282382,0.282737,0.611571,...,17.473173,19.512504,20.439059,22.980747,26.271087,NaN,NaN,NaN,NaN,NaN
FRA,0.458777,0.481306,0.438885,0.416919,0.378857,0.289521,0.293181,0.298481,0.294425,0.279043,...,3.524242,4.342710,4.576583,5.193969,6.196517,NaN,NaN,NaN,NaN,NaN
GBR,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,7.928430,9.955860,13.665173,17.505286,22.970305,NaN,NaN,NaN,NaN,NaN
IDN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,5.221981,4.838274,4.436163,4.821482,4.778532,NaN,NaN,NaN,NaN,NaN
IND,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,3.954730,4.643609,4.960653,5.173683,5.361011,NaN,NaN,NaN,NaN,NaN
ITA,3.396546,2.843294,2.671697,2.880818,2.734295,2.356243,2.261182,2.201376,2.136883,2.158344,...,12.353317,16.935196,20.575251,22.341038,22.505878,NaN,NaN,NaN,NaN,NaN
JPN,0.000000,0.000000,0.057801,0.021883,0.021135,0.039448,0.056671,0.107571,0.153757,0.157197,...,3.719216,4.050228,4.834342,6.300470,7.755688,NaN,NaN,NaN,NaN,NaN
KOR,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.553982,0.588396,0.835485,1.062715,1.503935,NaN,NaN,NaN,NaN,NaN
MEX,0.000000,0.000000,0.433962,1.129709,1.179310,1.218332,1.132819,1.049307,1.641298,1.366447,...,2.916258,3.410496,3.881598,4.643511,5.490168,NaN,NaN,NaN,NaN,NaN
RUS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.053371,0.049284,0.045954,0.069940,0.091027,NaN,NaN,NaN,NaN,NaN
SAU,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000368,0.000352,0.000321,0.000296,NaN,NaN,NaN,NaN,NaN
TUR,1.656272,1.556524,1.585513,1.535950,1.408180,0.880599,1.060053,0.630581,0.643815,0.584318,...,2.510975,3.069362,4.080715,4.755857,6.307132,NaN,NaN,NaN,NaN,NaN
USA,0.049549,0.099292,0.139811,0.146321,0.180294,0.191632,0.191986,0.151007,0.196130,0.239317,...,4.789611,5.486241,6.320009,6.900029,7.386955,NaN,NaN,NaN,NaN,NaN
ZAF,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.125975,0.130241,0.151269,0.902309,1.930403,NaN,NaN,NaN,NaN,NaN

In [50]:
electricity_production_renewable.info()

<class 'pandas.core.frame.DataFrame'>
Index: 19 entries, ARG to ZAF
Data columns (total 61 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   YR1960  9 non-null      float64
 1   YR1961  9 non-null      float64
 2   YR1962  9 non-null      float64
 3   YR1963  9 non-null      float64
 4   YR1964  9 non-null      float64
 5   YR1965  9 non-null      float64
 6   YR1966  9 non-null      float64
 7   YR1967  9 non-null      float64
 8   YR1968  9 non-null      float64
 9   YR1969  9 non-null      float64
 10  YR1970  9 non-null      float64
 11  YR1971  18 non-null     float64
 12  YR1972  18 non-null     float64
 13  YR1973  18 non-null     float64
 14  YR1974  18 non-null     float64
 15  YR1975  18 non-null     float64
 16  YR1976  18 non-null     float64
 17  YR1977  18 non-null     float64
 18  YR1978  18 non-null     float64
 19  YR1979  18 non-null     float64
 20  YR1980  18 non-null     float64
 21  YR1981  18 non-null     float64
 22  YR1982  18 non-null     float64
 23  YR1983  18 non-null     float64
 24  YR1984  18 non-null     float64
 25  YR1985  18 non-null     float64
 26  YR1986  18 non-null     float64
 27  YR1987  18 non-null     float64
 28  YR1988  18 non-null     float64
 29  YR1989  18 non-null     float64
 30  YR1990  19 non-null     float64
 31  YR1991  19 non-null     float64
 32  YR1992  19 non-null     float64
 33  YR1993  19 non-null     float64
 34  YR1994  19 non-null     float64
 35  YR1995  19 non-null     float64
 36  YR1996  19 non-null     float64
 37  YR1997  19 non-null     float64
 38  YR1998  19 non-null     float64
 39  YR1999  19 non-null     float64
 40  YR2000  19 non-null     float64
 41  YR2001  19 non-null     float64
 42  YR2002  19 non-null     float64
 43  YR2003  19 non-null     float64
 44  YR2004  19 non-null     float64
 45  YR2005  19 non-null     float64
 46  YR2006  19 non-null     float64
 47  YR2007  19 non-null     float64
 48  YR2008  19 non-null     float64
 49  YR2009  19 non-null     float64
 50  YR2010  19 non-null     float64
 51  YR2011  19 non-null     float64
 52  YR2012  19 non-null     float64
 53  YR2013  19 non-null     float64
 54  YR2014  19 non-null     float64
 55  YR2015  19 non-null     float64
 56  YR2016  0 non-null      float64
 57  YR2017  0 non-null      float64
 58  YR2018  0 non-null      float64
 59  YR2019  0 non-null      float64
 60  YR2020  0 non-null      float64
dtypes: float64(61)
memory usage: 9.2+ KB

In [52]:
electricity_production_renewable.drop(electricity_production_renewable.loc[:, :'YR1970'], axis = 1, inplace=True)
electricity_production_renewable.drop(electricity_production_renewable.loc[:, 'YR2016':], axis = 1, inplace=True)

### Output-negative

## Saúde

### Input

#### Current health expenditure per capita (current US$)

In [53]:
current_health_per_capita = read_data('SH.XPD.CHEX.PC.CD')
current_health_per_capita.head()

,YR1960,YR1961,YR1962,YR1963,YR1964,YR1965,YR1966,YR1967,YR1968,YR1969,...,YR2011,YR2012,YR2013,YR2014,YR2015,YR2016,YR2017,YR2018,YR2019,YR2020
economy,,,,,,,,,,,,,,,,,,,,,
ARG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1208.391602,1368.422974,1421.657593,1286.217651,1531.484253,1153.534058,1529.616211,1127.907227,NaN,NaN
AUS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5861.702637,6025.344727,5813.985352,5607.917969,4860.372070,4971.614746,5308.783203,5425.340332,NaN,NaN
BRA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1031.576172,957.007080,981.152832,1017.047119,781.809998,801.411316,935.299194,848.388855,NaN,NaN
CAN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5355.676270,5459.959473,5409.788086,5189.826660,4615.642090,4610.926270,4845.589844,4994.902344,NaN,NaN
CHN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,236.374924,281.677155,326.041595,359.309326,390.104095,395.359955,437.256744,501.059387,NaN,NaN

In [54]:
current_health_per_capita.info()

<class 'pandas.core.frame.DataFrame'>
Index: 19 entries, ARG to ZAF
Data columns (total 61 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   YR1960  0 non-null      float64
 1   YR1961  0 non-null      float64
 2   YR1962  0 non-null      float64
 3   YR1963  0 non-null      float64
 4   YR1964  0 non-null      float64
 5   YR1965  0 non-null      float64
 6   YR1966  0 non-null      float64
 7   YR1967  0 non-null      float64
 8   YR1968  0 non-null      float64
 9   YR1969  0 non-null      float64
 10  YR1970  0 non-null      float64
 11  YR1971  0 non-null      float64
 12  YR1972  0 non-null      float64
 13  YR1973  0 non-null      float64
 14  YR1974  0 non-null      float64
 15  YR1975  0 non-null      float64
 16  YR1976  0 non-null      float64
 17  YR1977  0 non-null      float64
 18  YR1978  0 non-null      float64
 19  YR1979  0 non-null      float64
 20  YR1980  0 non-null      float64
 21  YR1981  0 non-null      float64
 22  YR1982  0 non-null      float64
 23  YR1983  0 non-null      float64
 24  YR1984  0 non-null      float64
 25  YR1985  0 non-null      float64
 26  YR1986  0 non-null      float64
 27  YR1987  0 non-null      float64
 28  YR1988  0 non-null      float64
 29  YR1989  0 non-null      float64
 30  YR1990  0 non-null      float64
 31  YR1991  0 non-null      float64
 32  YR1992  0 non-null      float64
 33  YR1993  0 non-null      float64
 34  YR1994  0 non-null      float64
 35  YR1995  0 non-null      float64
 36  YR1996  0 non-null      float64
 37  YR1997  0 non-null      float64
 38  YR1998  0 non-null      float64
 39  YR1999  0 non-null      float64
 40  YR2000  19 non-null     float64
 41  YR2001  19 non-null     float64
 42  YR2002  19 non-null     float64
 43  YR2003  19 non-null     float64
 44  YR2004  19 non-null     float64
 45  YR2005  19 non-null     float64
 46  YR2006  19 non-null     float64
 47  YR2007  19 non-null     float64
 48  YR2008  19 non-null     float64
 49  YR2009  19 non-null     float64
 50  YR2010  19 non-null     float64
 51  YR2011  19 non-null     float64
 52  YR2012  19 non-null     float64
 53  YR2013  19 non-null     float64
 54  YR2014  19 non-null     float64
 55  YR2015  19 non-null     float64
 56  YR2016  19 non-null     float64
 57  YR2017  19 non-null     float64
 58  YR2018  19 non-null     float64
 59  YR2019  0 non-null      float64
 60  YR2020  0 non-null      float64
dtypes: float64(61)
memory usage: 9.2+ KB

In [55]:
current_health_per_capita.dropna(axis=1, inplace=True)

### Output

#### UHC service coverage index

In [57]:
UHC_service = read_data('SH.UHC.SRVS.CV.XD')
UHC_service

,YR1960,YR1961,YR1962,YR1963,YR1964,YR1965,YR1966,YR1967,YR1968,YR1969,...,YR2011,YR2012,YR2013,YR2014,YR2015,YR2016,YR2017,YR2018,YR2019,YR2020
economy,,,,,,,,,,,,,,,,,,,,,
ARG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,76.0,NaN,76.0,NaN,NaN,NaN
AUS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,86.0,NaN,87.0,NaN,NaN,NaN
BRA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,78.0,NaN,79.0,NaN,NaN,NaN
CAN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,88.0,NaN,89.0,NaN,NaN,NaN
CHN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,76.0,NaN,79.0,NaN,NaN,NaN
DEU,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,82.0,NaN,83.0,NaN,NaN,NaN
FRA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,78.0,NaN,78.0,NaN,NaN,NaN
GBR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,85.0,NaN,87.0,NaN,NaN,NaN
IDN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,53.0,NaN,57.0,NaN,NaN,NaN
IND,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,52.0,NaN,55.0,NaN,NaN,NaN
ITA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,81.0,NaN,82.0,NaN,NaN,NaN
JPN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,80.0,NaN,83.0,NaN,NaN,NaN
KOR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,85.0,NaN,86.0,NaN,NaN,NaN
MEX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,76.0,NaN,76.0,NaN,NaN,NaN
RUS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,71.0,NaN,74.0,NaN,NaN,NaN
SAU,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,73.0,NaN,74.0,NaN,NaN,NaN
TUR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,71.0,NaN,74.0,NaN,NaN,NaN
USA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,83.0,NaN,84.0,NaN,NaN,NaN
ZAF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,69.0,NaN,69.0,NaN,NaN,NaN

In [58]:
UHC_service.info()

<class 'pandas.core.frame.DataFrame'>
Index: 19 entries, ARG to ZAF
Data columns (total 61 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   YR1960  0 non-null      float64
 1   YR1961  0 non-null      float64
 2   YR1962  0 non-null      float64
 3   YR1963  0 non-null      float64
 4   YR1964  0 non-null      float64
 5   YR1965  0 non-null      float64
 6   YR1966  0 non-null      float64
 7   YR1967  0 non-null      float64
 8   YR1968  0 non-null      float64
 9   YR1969  0 non-null      float64
 10  YR1970  0 non-null      float64
 11  YR1971  0 non-null      float64
 12  YR1972  0 non-null      float64
 13  YR1973  0 non-null      float64
 14  YR1974  0 non-null      float64
 15  YR1975  0 non-null      float64
 16  YR1976  0 non-null      float64
 17  YR1977  0 non-null      float64
 18  YR1978  0 non-null      float64
 19  YR1979  0 non-null      float64
 20  YR1980  0 non-null      float64
 21  YR1981  0 non-null      float64
 22  YR1982  0 non-null      float64
 23  YR1983  0 non-null      float64
 24  YR1984  0 non-null      float64
 25  YR1985  0 non-null      float64
 26  YR1986  0 non-null      float64
 27  YR1987  0 non-null      float64
 28  YR1988  0 non-null      float64
 29  YR1989  0 non-null      float64
 30  YR1990  0 non-null      float64
 31  YR1991  0 non-null      float64
 32  YR1992  0 non-null      float64
 33  YR1993  0 non-null      float64
 34  YR1994  0 non-null      float64
 35  YR1995  0 non-null      float64
 36  YR1996  0 non-null      float64
 37  YR1997  0 non-null      float64
 38  YR1998  0 non-null      float64
 39  YR1999  0 non-null      float64
 40  YR2000  0 non-null      float64
 41  YR2001  0 non-null      float64
 42  YR2002  0 non-null      float64
 43  YR2003  0 non-null      float64
 44  YR2004  0 non-null      float64
 45  YR2005  0 non-null      float64
 46  YR2006  0 non-null      float64
 47  YR2007  0 non-null      float64
 48  YR2008  0 non-null      float64
 49  YR2009  0 non-null      float64
 50  YR2010  0 non-null      float64
 51  YR2011  0 non-null      float64
 52  YR2012  0 non-null      float64
 53  YR2013  0 non-null      float64
 54  YR2014  0 non-null      float64
 55  YR2015  19 non-null     float64
 56  YR2016  0 non-null      float64
 57  YR2017  19 non-null     float64
 58  YR2018  0 non-null      float64
 59  YR2019  0 non-null      float64
 60  YR2020  0 non-null      float64
dtypes: float64(61)
memory usage: 9.2+ KB

#### Condom use, population ages 15-24, male (% of males ages 15-24)

In [59]:
condom_use_15_24 = read_data('SH.CON.1524.MA.ZS')
condom_use_15_24

,YR1960,YR1961,YR1962,YR1963,YR1964,YR1965,YR1966,YR1967,YR1968,YR1969,...,YR2011,YR2012,YR2013,YR2014,YR2015,YR2016,YR2017,YR2018,YR2019,YR2020
economy,,,,,,,,,,,,,,,,,,,,,
ARG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AUS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
BRA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CAN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CHN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
DEU,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
FRA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
GBR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
IDN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
IND,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ITA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
JPN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
KOR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
MEX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
RUS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
SAU,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TUR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
USA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ZAF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [60]:
condom_use_15_24.info()

<class 'pandas.core.frame.DataFrame'>
Index: 19 entries, ARG to ZAF
Data columns (total 61 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   YR1960  0 non-null      float64
 1   YR1961  0 non-null      float64
 2   YR1962  0 non-null      float64
 3   YR1963  0 non-null      float64
 4   YR1964  0 non-null      float64
 5   YR1965  0 non-null      float64
 6   YR1966  0 non-null      float64
 7   YR1967  0 non-null      float64
 8   YR1968  0 non-null      float64
 9   YR1969  0 non-null      float64
 10  YR1970  0 non-null      float64
 11  YR1971  0 non-null      float64
 12  YR1972  0 non-null      float64
 13  YR1973  0 non-null      float64
 14  YR1974  0 non-null      float64
 15  YR1975  0 non-null      float64
 16  YR1976  0 non-null      float64
 17  YR1977  0 non-null      float64
 18  YR1978  0 non-null      float64
 19  YR1979  0 non-null      float64
 20  YR1980  0 non-null      float64
 21  YR1981  0 non-null      float64
 22  YR1982  0 non-null      float64
 23  YR1983  0 non-null      float64
 24  YR1984  0 non-null      float64
 25  YR1985  0 non-null      float64
 26  YR1986  0 non-null      float64
 27  YR1987  0 non-null      float64
 28  YR1988  0 non-null      float64
 29  YR1989  0 non-null      float64
 30  YR1990  0 non-null      float64
 31  YR1991  0 non-null      float64
 32  YR1992  0 non-null      float64
 33  YR1993  0 non-null      float64
 34  YR1994  0 non-null      float64
 35  YR1995  0 non-null      float64
 36  YR1996  1 non-null      float64
 37  YR1997  0 non-null      float64
 38  YR1998  0 non-null      float64
 39  YR1999  0 non-null      float64
 40  YR2000  0 non-null      float64
 41  YR2001  0 non-null      float64
 42  YR2002  1 non-null      float64
 43  YR2003  0 non-null      float64
 44  YR2004  0 non-null      float64
 45  YR2005  0 non-null      float64
 46  YR2006  1 non-null      float64
 47  YR2007  0 non-null      float64
 48  YR2008  0 non-null      float64
 49  YR2009  0 non-null      float64
 50  YR2010  0 non-null      float64
 51  YR2011  0 non-null      float64
 52  YR2012  0 non-null      float64
 53  YR2013  0 non-null      float64
 54  YR2014  0 non-null      float64
 55  YR2015  0 non-null      float64
 56  YR2016  0 non-null      float64
 57  YR2017  0 non-null      float64
 58  YR2018  0 non-null      float64
 59  YR2019  0 non-null      float64
 60  YR2020  0 non-null      float64
dtypes: float64(61)
memory usage: 9.2+ KB

#### Immunization, measles (% of children ages 12-23 months)

In [71]:
immunization = read_data('SH.IMM.MEAS')
immunization

,YR1960,YR1961,YR1962,YR1963,YR1964,YR1965,YR1966,YR1967,YR1968,YR1969,...,YR2011,YR2012,YR2013,YR2014,YR2015,YR2016,YR2017,YR2018,YR2019,YR2020
economy,,,,,,,,,,,,,,,,,,,,,
ARG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,95.0,94.0,94.0,95.0,89.0,90.0,89.0,94.0,94.0,NaN
AUS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,94.0,94.0,94.0,94.0,95.0,95.0,95.0,95.0,95.0,NaN
BRA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,99.0,99.0,98.0,97.0,96.0,95.0,91.0,92.0,91.0,NaN
CAN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,88.0,89.0,90.0,90.0,89.0,89.0,90.0,90.0,90.0,NaN
CHN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,99.0,99.0,99.0,99.0,99.0,99.0,99.0,99.0,99.0,NaN
DEU,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,97.0,97.0,97.0,97.0,97.0,97.0,97.0,97.0,97.0,NaN
FRA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,89.0,91.0,90.0,91.0,91.0,90.0,90.0,90.0,90.0,NaN
GBR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,90.0,92.0,93.0,93.0,93.0,92.0,92.0,92.0,91.0,NaN
IDN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,80.0,82.0,87.0,86.0,87.0,88.0,90.0,89.0,88.0,NaN
IND,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,84.0,83.0,83.0,85.0,87.0,88.0,90.0,93.0,95.0,NaN
ITA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,90.0,90.0,90.0,87.0,85.0,87.0,92.0,93.0,94.0,NaN
JPN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,94.0,96.0,95.0,98.0,96.0,96.0,97.0,97.0,96.0,NaN
KOR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,99.0,99.0,99.0,99.0,98.0,98.0,97.0,98.0,98.0,NaN
MEX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,98.0,99.0,89.0,97.0,97.0,96.0,76.0,97.0,73.0,NaN
RUS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,98.0,98.0,98.0,98.0,98.0,98.0,98.0,98.0,98.0,NaN
SAU,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,98.0,98.0,98.0,98.0,98.0,98.0,96.0,98.0,95.0,NaN
TUR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,98.0,96.0,98.0,94.0,97.0,98.0,96.0,96.0,97.0,NaN
USA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,92.0,91.0,92.0,92.0,92.0,92.0,92.0,92.0,90.0,NaN
ZAF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,77.0,79.0,78.0,84.0,86.0,85.0,70.0,70.0,72.0,NaN

In [72]:
immunization.info()

<class 'pandas.core.frame.DataFrame'>
Index: 19 entries, ARG to ZAF
Data columns (total 61 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   YR1960  0 non-null      float64
 1   YR1961  0 non-null      float64
 2   YR1962  0 non-null      float64
 3   YR1963  0 non-null      float64
 4   YR1964  0 non-null      float64
 5   YR1965  0 non-null      float64
 6   YR1966  0 non-null      float64
 7   YR1967  0 non-null      float64
 8   YR1968  0 non-null      float64
 9   YR1969  0 non-null      float64
 10  YR1970  0 non-null      float64
 11  YR1971  0 non-null      float64
 12  YR1972  0 non-null      float64
 13  YR1973  0 non-null      float64
 14  YR1974  0 non-null      float64
 15  YR1975  0 non-null      float64
 16  YR1976  0 non-null      float64
 17  YR1977  0 non-null      float64
 18  YR1978  0 non-null      float64
 19  YR1979  0 non-null      float64
 20  YR1980  10 non-null     float64
 21  YR1981  10 non-null     float64
 22  YR1982  10 non-null     float64
 23  YR1983  15 non-null     float64
 24  YR1984  15 non-null     float64
 25  YR1985  16 non-null     float64
 26  YR1986  16 non-null     float64
 27  YR1987  17 non-null     float64
 28  YR1988  17 non-null     float64
 29  YR1989  17 non-null     float64
 30  YR1990  18 non-null     float64
 31  YR1991  18 non-null     float64
 32  YR1992  19 non-null     float64
 33  YR1993  19 non-null     float64
 34  YR1994  19 non-null     float64
 35  YR1995  19 non-null     float64
 36  YR1996  19 non-null     float64
 37  YR1997  19 non-null     float64
 38  YR1998  19 non-null     float64
 39  YR1999  19 non-null     float64
 40  YR2000  19 non-null     float64
 41  YR2001  19 non-null     float64
 42  YR2002  19 non-null     float64
 43  YR2003  19 non-null     float64
 44  YR2004  19 non-null     float64
 45  YR2005  19 non-null     float64
 46  YR2006  19 non-null     float64
 47  YR2007  19 non-null     float64
 48  YR2008  19 non-null     float64
 49  YR2009  19 non-null     float64
 50  YR2010  19 non-null     float64
 51  YR2011  19 non-null     float64
 52  YR2012  19 non-null     float64
 53  YR2013  19 non-null     float64
 54  YR2014  19 non-null     float64
 55  YR2015  19 non-null     float64
 56  YR2016  19 non-null     float64
 57  YR2017  19 non-null     float64
 58  YR2018  19 non-null     float64
 59  YR2019  19 non-null     float64
 60  YR2020  0 non-null      float64
dtypes: float64(61)
memory usage: 9.2+ KB

In [73]:
immunization.drop(immunization.loc[:, :'YR1982'], axis = 1, inplace=True)
immunization.drop(['YR2020'], axis = 1, inplace=True)
immunization.fillna(immunization.mean(), inplace=True)

#### People using at least basic drinking water services (% of population)

In [74]:
basic_water_drink = read_data('SH.H2O.BASW.ZS')
basic_water_drink

,YR1960,YR1961,YR1962,YR1963,YR1964,YR1965,YR1966,YR1967,YR1968,YR1969,...,YR2011,YR2012,YR2013,YR2014,YR2015,YR2016,YR2017,YR2018,YR2019,YR2020
economy,,,,,,,,,,,,,,,,,,,,,
ARG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,98.613293,98.794950,98.852067,98.909320,98.966588,99.023858,NaN,NaN,NaN,NaN
AUS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,99.891969,99.900767,99.909588,99.961479,99.970006,99.969973,99.969934,99.969895,99.969856,99.969812
BRA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,96.787980,97.050980,97.307676,97.558582,97.803568,97.955839,98.450955,98.679495,98.935544,99.320853
CAN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,99.235894,99.234326,99.232686,99.230985,99.229221,99.227395,99.225538,99.223631,99.221650,99.221811
CHN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,89.268487,89.934559,90.571909,91.181354,91.762641,92.315998,92.840908,93.335884,93.813267,94.261111
DEU,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,100.000000,100.000000,100.000002,100.000000,100.000002,99.999998,99.999998,99.999998,100.000000,100.000002
FRA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,99.982178,99.988966,99.995587,100.000000,100.000000,100.000000,100.000000,100.000000,100.000003,99.999999
GBR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,99.999997,100.000001,99.999999,99.999999,100.000001,100.000001,100.000001,100.000001,99.999997,99.999999
IDN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,85.271449,86.097947,86.915914,87.725863,88.527353,89.320435,90.104624,90.880300,91.647290,92.415350
IND,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,86.182045,86.676561,87.167500,87.654765,88.138133,88.617406,89.092433,89.562937,90.028699,90.489525
ITA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,99.839897,99.865609,99.891322,99.917034,99.917034,99.917034,99.917034,99.917034,99.917034,99.917034
JPN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,98.766699,98.805725,98.844752,98.883779,98.922805,98.961832,99.000859,99.039886,99.078912,99.078912
KOR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,99.105826,99.197556,99.289286,99.381016,99.472746,99.564476,99.656206,99.747937,99.839667,99.931397
MEX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,96.271203,96.716444,97.157255,97.593626,98.025444,98.452865,98.875781,99.269132,99.477264,99.679568
RUS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,96.164824,96.254122,96.344285,96.435395,96.527155,96.619534,96.712421,96.805627,96.899034,96.992548
SAU,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,98.907726,99.067801,99.227876,99.387951,99.548026,99.708102,99.868177,100.000000,100.000000,100.000000
TUR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,95.587717,95.760487,95.929341,96.094540,96.256159,96.414322,96.569089,96.720609,96.868967,97.014269
USA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,99.074887,99.169688,99.263379,99.355881,99.447158,99.537139,99.625816,99.713121,99.799044,99.883527
ZAF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,90.104689,90.561754,91.009033,91.447280,91.876344,92.296293,92.707024,93.108635,93.501227,93.885057

In [75]:
basic_water_drink.info()

<class 'pandas.core.frame.DataFrame'>
Index: 19 entries, ARG to ZAF
Data columns (total 61 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   YR1960  0 non-null      float64
 1   YR1961  0 non-null      float64
 2   YR1962  0 non-null      float64
 3   YR1963  0 non-null      float64
 4   YR1964  0 non-null      float64
 5   YR1965  0 non-null      float64
 6   YR1966  0 non-null      float64
 7   YR1967  0 non-null      float64
 8   YR1968  0 non-null      float64
 9   YR1969  0 non-null      float64
 10  YR1970  0 non-null      float64
 11  YR1971  0 non-null      float64
 12  YR1972  0 non-null      float64
 13  YR1973  0 non-null      float64
 14  YR1974  0 non-null      float64
 15  YR1975  0 non-null      float64
 16  YR1976  0 non-null      float64
 17  YR1977  0 non-null      float64
 18  YR1978  0 non-null      float64
 19  YR1979  0 non-null      float64
 20  YR1980  0 non-null      float64
 21  YR1981  0 non-null      float64
 22  YR1982  0 non-null      float64
 23  YR1983  0 non-null      float64
 24  YR1984  0 non-null      float64
 25  YR1985  0 non-null      float64
 26  YR1986  0 non-null      float64
 27  YR1987  0 non-null      float64
 28  YR1988  0 non-null      float64
 29  YR1989  0 non-null      float64
 30  YR1990  0 non-null      float64
 31  YR1991  0 non-null      float64
 32  YR1992  0 non-null      float64
 33  YR1993  0 non-null      float64
 34  YR1994  0 non-null      float64
 35  YR1995  0 non-null      float64
 36  YR1996  0 non-null      float64
 37  YR1997  0 non-null      float64
 38  YR1998  0 non-null      float64
 39  YR1999  0 non-null      float64
 40  YR2000  17 non-null     float64
 41  YR2001  17 non-null     float64
 42  YR2002  18 non-null     float64
 43  YR2003  18 non-null     float64
 44  YR2004  18 non-null     float64
 45  YR2005  19 non-null     float64
 46  YR2006  19 non-null     float64
 47  YR2007  19 non-null     float64
 48  YR2008  19 non-null     float64
 49  YR2009  19 non-null     float64
 50  YR2010  19 non-null     float64
 51  YR2011  19 non-null     float64
 52  YR2012  19 non-null     float64
 53  YR2013  19 non-null     float64
 54  YR2014  19 non-null     float64
 55  YR2015  19 non-null     float64
 56  YR2016  19 non-null     float64
 57  YR2017  18 non-null     float64
 58  YR2018  18 non-null     float64
 59  YR2019  18 non-null     float64
 60  YR2020  18 non-null     float64
dtypes: float64(61)
memory usage: 9.2+ KB

In [81]:
basic_water_drink.drop(basic_water_drink.loc[:, :'YR1999'], axis = 1, inplace=True)
basic_water_drink.fillna(basic_water_drink.mean(), inplace=True)